### ISSUE TITLE
Multiple bluetooth dialogs being created on rotation

### ISSUE THREAD

**Issue by addiegupta** [fossasia/badge-magic-android#101]
**Describe the bug**

The AlertDialog asking for bluetooth permission is being recreated on rotation of the device.

**To Reproduce**

1 Open the app
2 Bluetooth alert dialog pops up
2 Rotate the device
3 Dismiss a dialog
4 An AlertDialog is still present

**Expected behavior**

Only one dialog should be present

**Logs**

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22665789/55246950-6242c780-526c-11e9-860e-e369ce8ac3dd.gif)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version| Pie 9.0    |

**Additional context**

**Would you like to work on the issue?**

Yes

**Comment by adityastic** [comment]
Just save the state and check for the changed state in oncreate. Well tested

**Comment by adityastic** [comment]
@addiegupta are you working on this issue?
