### ISSUE TITLE
No message shown on empty text preview click

### ISSUE THREAD

**Issue by sparrow007** [fossasia/badge-magic-android#105]
**Describe the bug**
There is no toast message when there is empty text and click on preview button.

**To Reproduce**
Click on preview button when no text written in edittext.

**Expected behavior**
There should be a toast message like "Write text for preview"

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A|
|Android Version|7.1.2    |

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
Duplicate of #65. I am already working on it.

**Comment by sparrow007** [comment]
@yashk2000 go ahead bro :)
