### ISSUE TITLE
Visibility of badge in landscape mode.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#106]
**Describe the bug**
In landscape mode, the badge preview is not fully visible.

**To Reproduce**
Shift to landscape mode.

**Expected behavior**
Badge preview should be completely visible.

**Screenshots**

![screencap](https://user-images.githubusercontent.com/41234408/55278802-127d0280-5337-11e9-859d-a2f12f27ee05.png)

**Additional Context**
The size of the text "Badge Magic" also decreases on the top. That should also not happen.

**Would you like to work on the issue?**
YES.

**Comment by adityastic** [comment]
Yes Sir, I you will to have to make it maintain the ratio to get this fixed.
