### ISSUE TITLE
Widget Overflow issue

### ISSUE THREAD

**Issue by Dhruv80576** [fossasia/badge-magic-android#1066]
Widget overflow issue during popups and change in screen orientation. 
Please find attached screenshot to verify issues.
![Screenshot_20241103_105829](https://github.com/user-attachments/assets/eccd8440-891e-45af-a64a-4fea17637ffb)
![Screenshot_20241103_110104](https://github.com/user-attachments/assets/78f5b8fc-77db-4d32-a487-a1dad2d60585)

**Comment by Dhruv80576** [comment]
can you assign it to me ?

**Comment by mariobehling** [comment]
Hi @Dhruv80576 thanks for reporting! We usually do not assign issues to new contributors. Simply make a PR, please. It is unlikely that there will be an overlap and someone else would take up an issue. Thank you!
