### ISSUE TITLE
No way to have static text

### ISSUE THREAD

**Issue by Dhruv80576** [fossasia/badge-magic-android#1088]
Currently there is no way to have static text on the Badge. I would like to implement it. Please share your views.

**Comment by adityastic** [comment]
Interesting, what do you mean by static text?

**Comment by Dhruv80576** [comment]
I mean there is no way to have simple non animating text or image on the badge rn

**Comment by adityastic** [comment]
Ah, the fixed animation? Isn't that just fixed on the badge? With no animations and just plain text printed?

**Comment by Dhruv80576** [comment]
Ohh my bad i didn't see it earlier.

**Comment by adityastic** [comment]
No worries, I'll close it for now
