### ISSUE TITLE
Keyboard should go down on pressing the enter button on keyboard.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#109]
**Describe the bug**
When the enter button is pressed on the keyboard, no action takes place and the keyboard stays up.

**Expected behavior**
The keyboard should go down.

**Additional context**
@iamareebjamal should it be made such that when the keyboard enter button is pressed, the preview starts appearing on the preview badge?

**Would you like to work on the issue?**

YES.

**Comment by theLimitBreaker** [comment]
Also when `Preview button` for text is clicked , keyboard still stays up. This could also be included

**Comment by theLimitBreaker** [comment]
@yashk2000  are you still working on this ?

**Comment by yashk2000** [comment]
Yes. I am working on this.

**Comment by theLimitBreaker** [comment]
cool  then please consider this too

> Also when Preview button for text is clicked , keyboard still stays up. This could also be included
