### ISSUE TITLE
Layouts overflow on small screen sizes

### ISSUE THREAD

**Issue by AsCress** [fossasia/badge-magic-android#1097]
**Actual Behaviour**
I happened to be testing the app using a Motorola G5 Plus (5.2" 424 ppi), and noticed that the _AnimationContainer_ and the _EffectsContainer_ layouts overflow on this screen size.

**Expected Behaviour**
The layouts should not overflow on any screen size.

**LogCat for the issue**
[log.txt](https://github.com/user-attachments/files/17789110/log.txt)

**Screenshots of the issue**
<div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
<img src="https://github.com/user-attachments/assets/ccc4f663-7265-4b1c-9707-18714ca587fd" width = "420" height = "800"/>
<img src="https://github.com/user-attachments/assets/6c82881e-de08-4590-b976-64bd293ed631" width = "420" height = "800"/>

Do let me know if I can help in any other way.

**Comment by adityastic** [comment]
@AsCress would you like to try and fix the ui elements causing overflow?

**Comment by AsCress** [comment]
@adityastic Yeah. I'd love to give that a try. You can go ahead and assign me the issue.
