### ISSUE TITLE
Only one checkbox is allowed to be checked

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#110]
**Describe the bug**
While setting the animations either one of flash or marquee is only being checked, not both at the same time.

**To Reproduce**
1. Open app
2. Type some text
3. Click flash and then click marquee

**Expected behavior**
Both must be allowed to be checked at the same time

**Logs**
N/A

**Screenshots**
![flash](https://user-images.githubusercontent.com/34381723/55284874-f57b1a80-539c-11e9-8f8d-80fc6c0b76fd.gif)

**Smartphone Info:**

| Device 	| Android Version 	|
|---------	|:---------------:	|
| Redmi 4 	| Android 7.1.2 	|

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
I made it that way xD

**Comment by yashk2000** [comment]
Actually, both boxes should be checkable. In the badge, flash and marquee can both be there at there the same time.

**Comment by yatri1609** [comment]
Exactly @yashk2000 I'll fix it no worries @adityastic

**Comment by adityastic** [comment]
Cool. Make sure you also change the animation in the badge preview. It depends on the option for flash and marquee

**Comment by yatri1609** [comment]
@adityastic Yeah I will do that too

**Comment by anhanh11001** [comment]
@yatri1609 are you still working on this or can I take up on this as I find this is a pretty fast issue to solve

**Comment by yatri1609** [comment]
@anhanh11001 yes I'm please look at other issues.
