### ISSUE TITLE
Changing Level or Mode when Preview Badge is displaying should take effect without having to click Preview Button to apply change

### ISSUE THREAD

**Issue by psalmfill** [fossasia/badge-magic-android#114]
**Describe the bug**

When text has been enter or image selected  and preview button clicked and preview Badge display active,
if Mode is change , preview Badge mode should change dynamically and also if speed is change Preview Badge speed should also be change dynamically without having to click the preview button to apply changes.

**To Reproduce**

Enter a text or select an image
click on preview
change level or mode (but preview Badge Configuration remains same)

**Expected behavior**
if Mode is change , preview badge mode should change dynamically and also if speed is change Preview Badge speed should also be affected dynamically without having to click the preview button for change to take place.

|               | |
|---------------|-|
|Device         |GIONEE M5|
|Android Version|LOLLIPOP 5.1  |

**Additional context**

**Would you like to work on the issue?**
I will very much like to work on this issue

**Comment by adityastic** [comment]
@psalmfill Sir. The preview button is not a toggle button, it is a click button which is there to preview the current mode and current speed.

**Comment by psalmfill** [comment]
@adityastic I know it's not a toggle button.
What i mean is that,  as the preview Badge is in display process,  if speed is changed , the preview Badge  speed is changed instantly or if the mode is changed , the preview Badge mode changed instantly
Without having to click preview to apply the change.

**Comment by adityastic** [comment]
@psalmfill great, good luck
