### ISSUE TITLE
Browse more drawables

### ISSUE THREAD

**Issue by akkywadhwa** [fossasia/badge-magic-android#118]
**Describe the feature you'd like**
The user must be able to browse more drawable images to draw on the LED.

**Screenshots**

**Additional context**

**Would you like to work on the issue?**
Yes, I am taking up this issue.

**Comment by adityastic** [comment]
@iamareebjamal Can I take this over?

**Comment by mariobehling** [comment]
Sorry, this idea is conflicting with the recent UI changes. Therefore closing it.
