### ISSUE TITLE
Flash is not working with left/right/up/down animation

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#132]
**Describe the bug**
Flash is not working with left/right/up/down animation, currently, it is only working with fixed

**Screenshots**
<img src="https://i.ibb.co/Jyk3KW6/56310267-2406842126016950-5889206779149025280-n.png" width="300">

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
Yes it has not been implemented. Go on
