### ISSUE TITLE
Removing preview button in drawable section

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#133]
**Describe the feature you'd like**
Currently, in order to preview a drawable, the user has to select on that and click preview. I think the preview button can be removed. The animation can start running right after the user clicks into the drawable and it can stop when the user clicks into that drawable again. This would make some more space for recycler view of selecting drawable

**Screenshots**
Here is the current view:
<img src="https://i.ibb.co/Jyk3KW6/56310267-2406842126016950-5889206779149025280-n.png" width="300">

@adityastic I'm starting to contribute to this project and for now I don't know who is the maintainer of the projects. I saw that you are really active on a lot of issues and PRs, so are you the maintainers and who else should I know? Thanks!

By the way, please gives your thought on this

**Comment by adityastic** [comment]
I am not the maintainer, I too am a contributor. You can work on this issue too, If you need any help let me know

**Comment by adityastic** [comment]
I just forgot, this is referenced in #114

**Comment by anhanh11001** [comment]
@adityastic oh yeah, I'm not surprised that other contributors have also come up with that
