### ISSUE TITLE
Inverted LED effect 

### ISSUE THREAD

**Issue by akkywadhwa** [fossasia/badge-magic-android#134]
**Describe the feature you'd like**
For any character example "A", all the LEDs which were ON in normal mode would be turned off and vice versa.

**Screenshots**
![Screenshot_20190403-163530_Badge Magic](https://user-images.githubusercontent.com/666752/55474739-9ed93f00-562f-11e9-8d4e-55fda4b09bfa.jpg)

**Would you like to work on the issue?**
Yes, I am working on this and have completed the work partially.

**Comment by adityastic** [comment]
Looks Great

**Comment by adityastic** [comment]
@akkywadhwa any updates?

**Comment by adityastic** [comment]
@iamareebjamal, can I take this issue?

**Comment by iamareebjamal** [comment]
Go ahead
