### ISSUE TITLE
Cannot send the drawables

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#139]
**Describe the bug**
In the MessageActivity.kt, when here is a part of the code inside `send.setOnClickListener` when clicking Send button:
```
if (content.text.isEmpty()) {
    presenter.sendBitmap(this, BitmapFactory.decodeResource(resources, R.drawable.mix2))
    showLoaderView(false)
} else {
    presenter.sendMessage(this, convertToDeviceDataModel())
    showLoaderView(true)
}
```
This means that currently the app only check if there is text to send, otherwise, it will a default drawable R.drawable.mix2 -> Cannot send a selected drawable

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
Yes, There need to be a design change before we can implement this, currently to fix this we need to make radio buttons for text and drawable and check which one is selected. This is against the experience, that is the reason I left it

**Comment by yashk2000** [comment]
@anhanh11001 I agree with @adityastic. This change does not simply require that empty edittext condition to be removed.

**Comment by adityastic** [comment]
I am currently working on it. It was a part of the drawable section which was merged some days before, please let me complete it

**Comment by anhanh11001** [comment]
@yashk2000 Yeah I agree that there is no need to remove the empty edittext condition and I didn't mean it either. What I'm suggesting is to add another boolean statement to check whether the user has previewed and chosen a drawable so that we can send it. 
@adityastic I don't quite understand what do you mean by "against the experience". Can you explain it? Thank you and let me know if I can help anything

**Comment by adityastic** [comment]
@anhanh11001 The app needs to be clean in terms of experience, I am planning to add different sections for both the features. The Text and Drawable section will be separated from this screen, currently all the app functions are inside this single activity, which makes it harder for people to use it.

**Comment by anhanh11001** [comment]
@adityastic ok, I will close this issue now but I think if you want to split Text and Drawable into different sections, which sounds like a big change then I think you can open an issue so that other contributors like me can also discuss on that!

**Comment by adityastic** [comment]
@anhanh11001 sure. Will do it tomorrow
