### ISSUE TITLE
Implement a badge preview on the top of the screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#14]
There are a number of apps to use the phone as an LED screen. Please take inspiration and implement a preview screen to show how it will look on the actual device on the top. Compare for example to this app: https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

**Comment by dilum1995** [comment]
Hello @mariobehling ,

Is it possible for me to work on this and also to improve the application UI?

**Comment by mariobehling** [comment]
Please go ahead. As this project is still early stage there is no need to ask if you can take over an issue. Simple get started according to your interests. Thank you.
