### ISSUE TITLE
Animation running left/right/up/down doesn't go over the screen

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#144]
**Describe the bug**
When choosing animation on left/right/up/down, the drawable/words don't go all the way but only go half of the screen and then stop

**Screenshots**
<img src="https://i.ibb.co/1qrz42q/ezgif-4-3527443b7b51.gif" width="300">

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
Yes sir, this might be great. Good luck
