### ISSUE TITLE
Add options to change the color of the LED

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#149]
**Describe the feature you'd like**
Add options to change the color of the LED

**Would you like to work on the issue?**
Yes

**Comment by yashk2000** [comment]
How well the color change in LED be transferred to the real device?

**Comment by anhanh11001** [comment]
@yashk2000 to be honest, I don't know. I won't say it is impossible or not because I haven't worked with the hardware yet. But if the hardware can work with the LED light changes than I think that should be a different issue/PR
@iamareebjamal please gives your thought?

**Comment by yashk2000** [comment]
I think some changes in the hardware also will be needed for this. As of yet, I have seen no option for different colors. I guess we should wait before Implementing this feature because if it cannot be done in the hardware, it is of no use.

**Comment by yashk2000** [comment]
And since it is a LED hardware, it will support different colors for sure, but we need to figure out how before implementing this feature.

**Comment by adityastic** [comment]
@yashk2000 The LED's with different color are sold differently.

**Comment by adityastic** [comment]
@anhanh11001 can we close this?
