### ISSUE TITLE
Feature for Theme Support

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#150]
**Describe the feature you'd like**
Currently, The app does not have any themes. I would like to add options in the app to choose the base theme between
- Automatic by current time
- Day
- Night
- Night when Battery Low

And the Accents for the app between several color combinations
These Accents will Cover:
- Accents around the complete application
- Accents of the preview badge

**Would you like to work on the issue?**
Yep. Happy Theming

**Comment by mariobehling** [comment]
Please avoid this feature as we don't want to focus resources on maintaining it. It is low priority and out of scope.
