### ISSUE TITLE
Adding the remaining animations

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#152]
**Feature Description**
Current Animations are not working in preview:
- Animation
- Laser
- Snowflake
- Picture

**Animations I plan to work on:**
- [x] Animation
- [x] Laser

**Animations @anhanh11001 will to work on:**
- [x] Snowflake
- [x] Picture

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
Are you still working on this or can we split the work in here so that I can work on making 1 or 2 animations?

**Comment by adityastic** [comment]
@anhanh11001 Currently 4 animations are remaining:
Animation
Laser
Picture
Snowflake

Let's divide it. I can work on Animation and Laser and you can work on Picture and Snowflake

**Comment by adityastic** [comment]
@anhanh11001 are you planning to work on Picture animation mode?

**Comment by anhanh11001** [comment]
@adityastic will send the PR tomorrow, I was in the test week last week so I didn't have time to do anything, will continue to work from now on!!

**Comment by adityastic** [comment]
@anhanh11001 great
