### ISSUE TITLE
Remove code smells from app

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badge-magic-android#154]
- [ ] Remove any use of `Any`. This is not a dynamic language project, there is no need to return `Any` type from anywhere
- [ ] Use List instead of ArrayList. NEVER return or accept implementation details/concrete classes, use abstractions
- [ ] Remove casts wherever used. There is not a single instance where code written by us will use a cast. As with any use of cast by now in this project, it is just a mistake on the part of developer to first return Any or ArrayList and then cast to appropriate types

**Comment by adityastic** [comment]
Would love to take this issue
