### ISSUE TITLE
Add LEFT-RIGHT Animation

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#158]
**Describe the feature you'd like**
Add an animation for drawable/text to toggle by going the the left and the turn right when meet the Preview edge and vice versa
Also, I will come up with a better name if possible
**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
I'm afraid the hardware does not have this included inside it. It won't be possible unless the hardware supports it.
