### ISSUE TITLE
Implement animations

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#16]
There are a number of nice animations possible with LED. Please check out this app and implement animations that work on real devices: https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

**Comment by theLimitBreaker** [comment]
@mariobehling  There are animations like `Bounce` , `Rotate X` , `Rotate Y` or `Blink`  which are still not in preview listv. Could I add these and work on these ?

**Comment by yashk2000** [comment]
@theLimitBreaker when you implement animations, make sure that they will appear on the device too.

**Comment by adityastic** [comment]
@theLimitBreaker the hardware has support for 8 animations currently. It would be better if you could complete them

**Comment by theLimitBreaker** [comment]
@adityastic  I don't understand the limit of animations being 8 . Could you please elaborate ?

**Comment by adityastic** [comment]
@theLimitBreaker The hardware has support for 8 animations currently. Check the specifications of the hardware, it says compatible with 8 modes. Example, If we send 1 from bluetooth it sets the animation to 1, if we set 8 through bluetooth, it sets it to 8. There is no 9th option supported by the device.

**Comment by adityastic** [comment]
@theLimitBreaker the preview just tries to mimic the exact animations those animations are not currently being sent to the hardware right now

**Comment by theLimitBreaker** [comment]
@adityastic  I am unable to see the specifications on website mentioned in README.md . Where can i see these spefications of hardware

**Comment by adityastic** [comment]
@iamareebjamal, I specified a way to achieve custom animations in my gsoc application which took an approach of sending 8 frame animations to the badge, as the badge only accepts 8 strings. If we send the perfect strings which act like an animation, we can create some amazing animations. Please give your thoughts on this sir

**Comment by mariobehling** [comment]
Let's simplify this and follow up here please: https://github.com/fossasia/badge-magic-android/issues/232
