### ISSUE TITLE
Sending of byte data when No data (text or bitmap) selected

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/badge-magic-android#163]
**Describe the bug**
Byte data is being sent when no data(text or byte date) is selected 

**To Reproduce**
Click on `send` button without selecting anything

**Expected behavior**
check should be placed before emitting data.
A dialog or prompt should be shown to user to select data 

**Logs**
`
2019-04-06 12:13:03.154 19300-19300/com.nilhcem.blenamebadge I/MessagePresenter: ByteData: [77616E67000000000400000000000000, 00050000000000000000000000000000, 000000000000E304060C0D0300000000, 00000000000000000000000000000000, 001E3121033B67430D18133E7F9C082A, 9CFFFFFFFF7F003CC64260EEF3E1D88C, 640000020103060F0B0A010000000810, F8ECFEFA0AB000000000000000000000]`

**Screenshots**
<img src="https://user-images.githubusercontent.com/24780524/55665950-2e1b6800-5865-11e9-94ae-469d8ecc0171.gif" width=360>

**Smartphone Info:**
|Device         |Nokia 6.1|
|Android Version| Android 9.0  |

**Would you like to work on the issue?**

yes .

**Comment by yashk2000** [comment]
That is supposed to happen. If send is clicked when no data is selected, a default bitmap appears on the device. I have a physical BLE device and have tested this on that. Please close the issue as it is not relevant.

**Comment by theLimitBreaker** [comment]
I agree with `default` message (text or bitmap) shouldn't separate `Test button` should be placed for users (To avoid confusion) . I didn't select any data and its sending default . User should be notified .
Make `Test Button` for showing default message. Show user `Default Bitmap will be shown`

**Comment by yashk2000** [comment]
Not needed. That will make the UI more clustered. When the user presses preview without entering any data, the default bitmap is shown. That's enough indication what will be shown when send is pressed.

**Comment by theLimitBreaker** [comment]
ok then . closing this issue
