### ISSUE TITLE
Make only one Preview button

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#169]
**Describe the feature you'd like**
Only one preview button will make the app more user friendly while having two preview button doesn't look good for now.

**Additional context**
The preview button will be besides the current Send button.

**Would you like to work on the issue?**
YES

**Comment by yashk2000** [comment]
@yatri1609 I do not think it should be done. Either text or bitmap can be previewed. If a single button is made, it will be confusing for the user to know that only one of the items can be previewed at once. For now, it will be better to let there be 2 separate buttons.
@adityastic can you also please give your views?

**Comment by yatri1609** [comment]
> @yatri1609 I do not think it should be done. Either text or bitmap can be previewed. If a single button is made, it will be confusing for the user to know that only one of the items can be previewed at once. For now, it will be better to let there be 2 separate buttons.
> @adityastic can you also please give your views?

I think having 1 preview button also makes it clear enough for user that just one can be previewed. I don't think there is need of two buttons as such.

**Comment by yashk2000** [comment]
How is it clear with just one button? If you place just one button, the user might think that both the things can be previewed at once. It won't be very good UX to use only one button.

**Comment by yatri1609** [comment]
I think that the main aim of having a preview button is to preview the look of the badge and having one makes UI more sleek and I think we can put a toast message that currently text is being previewed or so. @iamareebjamal @CloudyPadmal What do you think of having just one preview button ?

**Comment by adityastic** [comment]
Hey guys, check #151. It fixes this issue of buttons. I think this might be the better solution. What do you guys say? @yashk2000 @yatri1609 @iamareebjamal

**Comment by yashk2000** [comment]
@adityastic that's what I think should be done. That is the only way to make the app less clustered.

**Comment by yatri1609** [comment]
@yashk2000 @adityastic I think we should also take some ideas from the mentors. Also adding bottom tab is a good idea I think, and @adityastic we both can work together on it.

**Comment by adityastic** [comment]
@yatri1609 yes, we can create a bottom navigation with viewpager. @yashk2000, you and me, all three of us can work on this. This would be an amazing experience

**Comment by yatri1609** [comment]
Great ! @adityastic  I'll start with the bottom tab basic layout then and we can keep improvising it all through out, and put the issue breakdown and milestones.

**Comment by adityastic** [comment]
ok, great. get the bottombar working.

**Comment by adityastic** [comment]
@yatri1609 is the bottombar done?

**Comment by yashk2000** [comment]
@adityastic if you were already working on the bottom bar and are already done with it, I guess you can open a pr for that.

**Comment by adityastic** [comment]
@yashk2000 alright
