### ISSUE TITLE
Add feature to display bitmap

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#17]
Please implement the possibility to send a Bitmap to the LED badge directly. Since we have a full control over the badge device, we can create a 40x11px bitmap and write some code to convert it into byte arrays we can send to the LED badge.

![screenshot from 2018-12-17 08-00-16](https://user-images.githubusercontent.com/1583873/50071364-d253a300-01d1-11e9-9b80-34bbe5388a41.png)

![09_final](https://user-images.githubusercontent.com/1583873/50071516-4beb9100-01d2-11e9-8151-326c4accb1d3.jpg)

**Comment by anshulmak** [comment]
I think we can implement this by converting the bitmap to byte array via function -

    fun convertBitmapToByteArrayUncompressed(bitmap: Bitmap) : ByteArray? {
        val byteBuffer : ByteBuffer? = ByteBuffer.allocate(bitmap.byteCount)
        bitmap.copyPixelsToBuffer(byteBuffer)
        byteBuffer?.rewind()
        return byteBuffer?.array()
    }

and send this Byte Array to Led Badge.

**Comment by iamareebjamal** [comment]
Go ahead. First verify if it does work

**Comment by adityastic** [comment]
I am willing to work on it. I can write the code to convert any 40x 11 gray-scaled image to byte arrays which can then be sent to the LED Badge
