### ISSUE TITLE
Either text or drawable must be enabled

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#170]
**Describe the bug**
Currently when in portrait mode, both can be selected but when we write down text and preview it the drawable highlight must go away.

**To Reproduce**
1. Open app
2. click on any drawable and preview it.
3. Type any text and preview it

Here still the drawable will be highlighted.

**Expected behavior**
The drawable must not be highlighted once the text is previewed.

**Logs**
N/A

**Screenshots**
![Screenrecorder-2019-04-06-19-12-42-321](https://user-images.githubusercontent.com/34381723/55670418-853f2e00-58a1-11e9-8d9e-637fea1f7e23.gif)

**Smartphone Info:**

| Device 	| Android Version 	|
|---------	|:---------------:	|
| Redmi 4 	| Android 7.1.2 	|

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
#151 will fix it @yatri1609 . Different sections will make the app cleaner

**Comment by yatri1609** [comment]
@CloudyPadmal @iamareebjamal Do you think I should move forward with this?
