### ISSUE TITLE
Implement a Full screen preview of Animation

### ISSUE THREAD

**Issue by KaenDagger** [fossasia/badge-magic-android#175]
**Describe the feature you'd like**
Implement a Full screen preview of Animation

**Additional context**
This will give more closer view to real LED Badge

**Would you like to work on the issue?**

Yes

**Comment by adityastic** [comment]
Hey Sir, I didn't get that. If you rotate the device, the preview almost covers the whole device

**Comment by theLimitBreaker** [comment]
Hello @adityastic  sorry for being late to respond 
I meant this, Its taking full screen . Currently a part of other buttons is still visible 

![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/24780524/56074535-5578b480-5dd2-11e9-91b0-df1c38979fa8.gif)

**Comment by adityastic** [comment]
Oh. That's great

**Comment by adityastic** [comment]
Good luck with it

**Comment by adityastic** [comment]
@theLimitBreaker any updates?

**Comment by theLimitBreaker** [comment]
@adityastic sorry a little busy with exams . I would get to this.

**Comment by adityastic** [comment]
@theLimitBreaker, I would like to implement it using a pinch to zoom gesture. If you allow I can work on it

**Comment by theLimitBreaker** [comment]
NP . Why pinch to zoom ? Its badge animation . What will pinch to zoom will do .

**Comment by adityastic** [comment]
@theLimitBreaker, how do you want me to implement it then?, when you double tap the preview? or long press?

**Comment by theLimitBreaker** [comment]
A simple transparent full-screen icon. User would be able to see and understand . 
Also double tap would be fine .

**Comment by adityastic** [comment]
@iamareebjamal Please add a later tag to this issue

**Comment by yashk2000** [comment]
@adityastic is this feature really needed? On rotation, the badge is almost full screen. It is pretty clear without pinch to zoom or anything. If a full-screen icon is implemented, it's not like the badge would occupy the entire screen.
What's your opinion on this?

**Comment by adityastic** [comment]
Yes true, should be closed
