### ISSUE TITLE
Keyboard does not pop up automatically when shifting to text mode.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#186]
**Describe the bug**
On shifting from drawble to text mode, keyboard does not pop up automatically.

**Expected behavior**
Keyboard should pop up automatically.

**Would you like to work on the issue?**

YES.

**Comment by adityastic** [comment]
@yashk2000 Fix #109 with this too

**Comment by yashk2000** [comment]
@adityastic I'll do that.
