### ISSUE TITLE
Keyboard pops up on screen rotation in drawables mode.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#192]
**Describe the bug**
When the phone is rotated in drawable mode, the keyboard pops up.

**To Reproduce**
Shift to drawables mode, rotate the phone.

**Expected behavior**
The keyboard should not pop up.

**Would you like to work on the issue?**
YES.

**Comment by adityastic** [comment]
Why not just add it to the current pr. The issue is of same genre

**Comment by yashk2000** [comment]
@adityastic I shall try to fix #130 too. That's why I plan on making a separate pr.

**Comment by adityastic** [comment]
Great. That would be a better idea. Good luck

**Comment by adityastic** [comment]
@yashk2000 Its fixed by me already

**Comment by adityastic** [comment]
@yashk2000 I accidentally fixed your issue. Im so sorry

**Comment by yashk2000** [comment]
No problem @adityastic. I'll close this issue.
