### ISSUE TITLE
Creating app shortcuts for the app.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#199]
**Describe the feature you'd like**
When the app icon is long pressed, there are no shortcuts. Shortcuts to directly enter the text or drawable mode can be provided.

**Additional context**
@iamareebjamal  @adityastic what are your views? Should I proceed with this?
 
**Would you like to work on the issue?**
YES.

**Comment by adityastic** [comment]
As a feature I would love to implement it. But currently our app only has a single screens. App shortcuts were made to resolve the navigation depth issue

**Comment by adityastic** [comment]
Let me know your thoughts on it @yashk2000 . This feature is great, but is it necessary?

**Comment by mariobehling** [comment]
As we dont have many screens it does not seem required currently. Closing it therefore.
