### ISSUE TITLE
Issue when edittext is empty and send is clicked.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#203]
**Describe the bug**
When edit text is empty and send is clicked, data is sent to the device, but nothing is being displayed.

**To Reproduce**
Click send when edit text is empty.

**Expected behavior**
A default message or bitmap should be displayed or a toast should be shown, telling the user that edittext cannot be empty.

**Additional context**
@adityastic @iamareebjamal should I display a default bitmap or a toast?

**Would you like to work on the issue?**

YES.

**Comment by adityastic** [comment]
Toast would be a great idea

**Comment by yashk2000** [comment]
Ok.
