### ISSUE TITLE
Horizontal variation for the app

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#209]
**Describe the feature you'd like**
Currently, the horizontal view of the app is really bad as space is not used sufficiently 

**Screenshots**
Current view
<img src="https://i.ibb.co/qpMLqHD/57821678-1553958598067566-6494120397003292672-n.jpg" alt="57821678-1553958598067566-6494120397003292672-n" border="0">
<img src="https://i.ibb.co/KmjTzRS/58939919-2625309827542308-9175522390325592064-n.jpg" alt="58939919-2625309827542308-9175522390325592064-n" border="0">

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
Yeah, another layout would be a nice idea. We are not utilizing the space correctly
