### ISSUE TITLE
App crash on saving in horizontal screen

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#211]
**Describe the bug**
On horizontal screen, app crash when users try to save a configuration

**Screenshots**
<img src="https://i.ibb.co/VLZQjWt/ezgif-4-ab2d37d00807.gif" alt="ezgif-4-ab2d37d00807" border="0">

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
@anhanh11001 any updates on the picture animation?

**Comment by anhanh11001** [comment]
Actually I'm having a bit of problem on that, it is pretty hard for me, I'm doing some refractoring with the Badge Preview class

**Comment by anhanh11001** [comment]
I'm in class but I will private message you later to discuss on that

**Comment by adityastic** [comment]
Cool
