### ISSUE TITLE
Back press from saved section should lead back to main section.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#216]
**Describe the feature you'd like**
Currently, on clicking the back press in the saved section, the app exits. Instead, it should be directed back to the main activity.

**Would you like to work on the issue?**
YES.

**Comment by yashk2000** [comment]
@adityastic @anhanh11001 what are your views on this?

**Comment by adityastic** [comment]
If we have a bottom bar for navigation, this is not needed

**Comment by yashk2000** [comment]
Yeah, that's right. I'll close this.
