### ISSUE TITLE
Refractoring the codebase

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#219]
**Describe the bug**
Currently, there are some following improvements that can be made to improve the codebase:
- Extract resource (dimen, string,...)
- Refractor on naming
- Redundant methods (some methods can be merge into a shorter one)
- Unnecessary variable creation
- Some variable/function can be private
- Put hard-coded drawable file into a different folder:
Currently, we are calling default drawables by this. I think a better solution is to put those default drawables in a different folder and then iterate all of the drawables inside that folder to add to the adapter
```
DrawableInfo(resources.getDrawable(R.drawable.apple)),
DrawableInfo(resources.getDrawable(R.drawable.clock)),
DrawableInfo(resources.getDrawable(R.drawable.dustbin)),
DrawableInfo(resources.getDrawable(R.drawable.face)),
DrawableInfo(resources.getDrawable(R.drawable.heart)),
DrawableInfo(resources.getDrawable(R.drawable.home)),
...
```

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
Yes, I did saw the Resource Class you created and linked it to the application context. That would really simplify the code.

**Comment by adityastic** [comment]
I'd still suggest you to use extension functions. https://stackoverflow.com/questions/35317940/when-should-one-prefer-kotlin-extension-functions, have a read.

**Comment by adityastic** [comment]
About the Drawables, If we want to store them to a folder. We need to either make the user download the drawables or copy them to the folder on the first run. 
Letting the users download configuration from the server was in my GSoC proposal, @CloudyPadmal said me to focus on making the application stable first. If you copy it to a folder, you still have to keep it inside the application.

**Comment by adityastic** [comment]
@anhanh11001 I would like to contribute by implementing MVP Architecture throughout the application

**Comment by anhanh11001** [comment]
@adityastic so my point about keyboard is that, let's say we want to turn up the keyboard for writing text. Currently, we have to call `text_to_send.showKeyboard()`, which is weird because:
1. The action of calling showKeyboard() doesn't have anything to do with a view.
2. if text_to_send is somehow null (which is unpredictable), then the app crashes.

**Comment by anhanh11001** [comment]
@adityastic on MVP Architecture, of course please go ahead if you find any improvements.

On drawables, I'm still a little bit vague on my solution so let's skip this for now. But I do agree on  downloading configuration from the server is a little bit ambitious for now

**Comment by anhanh11001** [comment]
oh wait, I was wrong on the keyboard part, yeah, keeping it

**Comment by adityastic** [comment]
@anhanh11001 Great, I'll get started with MVP then, you can refractor the code.

**Comment by iamareebjamal** [comment]
https://duckduckgo.com/?q=refractor&t=canonical&ia=definition

**Comment by iamareebjamal** [comment]
@adityastic MVVM

**Comment by adityastic** [comment]
> https://duckduckgo.com/?q=refractor&t=canonical&ia=definition

Im so sorry, refactor*

**Comment by adityastic** [comment]
> @adityastic MVVM

Ok Sir, I will try to follow the MVVM architecture

**Comment by ShridharGoel** [comment]
@adityastic If you are refactoring to MVVM then please try to implement LiveData too

**Comment by adityastic** [comment]
@ShridharGoel Saved configuration Fragment has a recycler view and I implemented livedata with observer already in it. It's working :). Only the main activity is left, will be done by tomm

**Comment by ShridharGoel** [comment]
@adityastic Great

**Comment by adityastic** [comment]
Unfortunately the rest of the app is static, so a viewholder with a data access object works fine there
