### ISSUE TITLE
Layout of empty saved configurations.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#222]
**Describe the feature you'd like**
Currently, when the saved configurations is empty, there is nothing being displayed. If the saved configurations activity is empty, it should display a message on the screen that there are no saved configurations.

**Would you like to work on the issue?**
YES.

**Comment by adityastic** [comment]
What if the user wants to save only the marquee and no text. That effect looks cool though xD

**Comment by yashk2000** [comment]
I meant when there are no saved configurations at all. It is empty. Then a message should be on the screen saying "No configurations have been saved yet"

**Comment by adityastic** [comment]
Im so sorry, I misinterpreted it. When do you plan to show this message? everytime the user opens the app?

**Comment by yashk2000** [comment]
No, nothing like that. I'll display a message in the fragment itself by creating a different UI for empty view.

**Comment by adityastic** [comment]
That would be great

**Comment by yashk2000** [comment]
That'll be really cool. Definitely doing that.

**Comment by mariobehling** [comment]
There is no need to save configurations. We only save badges.
