### ISSUE TITLE
Change "Mode" to visual interpretation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#232]
To control the direction of the text moving the user currently has to choose from a drop down menu "Mode". Instead of the mode, please implement a visual interface that shows a small animation similar to https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

![Screenshot from 2019-05-01 15-16-53](https://user-images.githubusercontent.com/1583873/57008739-d0402d00-6c24-11e9-89ce-7bb917ddb0d6.png)

See "Mode" below

![Screenshot from 2019-04-25 00-22-03](https://user-images.githubusercontent.com/41234408/56267047-592a7500-610b-11e9-9947-5ce4edcdb66a.png)

**Comment by adityastic** [comment]
That's cool. Would love to work on it.
