### ISSUE TITLE
Implement "Speed Wheel"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#233]
To control the speed of the text moving the user currently has to choose from a drop down menu "Mode". Instead please implement a visual interface for the speed.

Make it into a circle "wheel". The more to the right the user turns the faster it gets. 

![Screenshot from 2019-04-25 00-22-03](https://user-images.githubusercontent.com/41234408/56267047-592a7500-610b-11e9-9947-5ce4edcdb66a.png)

**Comment by adityastic** [comment]
I would like to work on it

**Comment by yashk2000** [comment]
@adityastic can I work on this issue?

**Comment by adityastic** [comment]
@yashk2000 Definitely, I'll pick another issue. Good Luck

**Comment by yashk2000** [comment]
@mariobehling can you please give us an idea/mockup of the kind of wheel needed here?

**Comment by adityastic** [comment]
![20190501_232542](https://user-images.githubusercontent.com/11988517/57032803-d6f09380-6c68-11e9-9fcb-f3ac36d4bd3e.jpg)
 @mariobehling does this match your idea?

**Comment by yashk2000** [comment]
![image](https://user-images.githubusercontent.com/41234408/57032978-36e73a00-6c69-11e9-98e3-e348ed4d1de2.png)

Or something like this?

**Comment by adityastic** [comment]
@mariobehling yes sir, any mockups would be useful

**Comment by mariobehling** [comment]
Here is an example. 

![rotary_knob_android_custom_control](https://user-images.githubusercontent.com/1583873/57116925-da7c3b80-6d8a-11e9-9967-4c8dab2852e9.jpg)

**Comment by adityastic** [comment]
Great Sir. @mariobehling I am planning to redesign the app according to the new interface. I will be working full day and get it done by today. Can I work on it after the redesign? @mariobehling

**Comment by adityastic** [comment]
@mariobehling let me do it first for you :)
