### ISSUE TITLE
App requires access to location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#234]
The app should not require access to location info.

**Comment by adityastic** [comment]
@mariobehling Google has made it mandatory from Android 6.0 onwards. According to them location permission is necessary for hardware identification

Here is a link to the developers site : https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling Please check my comment

**Comment by adityastic** [comment]
@mariobehling hello sir, please read my comment above
