### ISSUE TITLE
Instead of "play" button we need a button "transfer/upload to device"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#235]
The red play button is not suitable for the transfer functionality. As a first step to simplify the UI, please implement a button "Transfer" next to the "Save" button in the UI.

**Comment by adityastic** [comment]
@mariobehling Hello Sir, currently the floating red button is responsible for sending configuration to the led for both the sections in the application, if we create a button transfer next to the save button inside the app like it use to be earlier, we would have to create another button inside the 'saved configuration' section for transferring data. Are you sure having two buttons for a single operation will simplify the user interface sir?

**Comment by adityastic** [comment]
What about changing the icon of the button, and making something which relates more to transfer than the current play button?

**Comment by adityastic** [comment]
Sir Currently, the send button handles both the sections inside the application. If we add a button  next to the send button, we would have to add another button in the saved badge section, and as it is a list we will have to make the button at the top. Are you sure this will simplify the interface?

**Comment by adityastic** [comment]
What if we change the sending icon from the play button to something which more resembles to transfering ?

**Comment by mariobehling** [comment]
Please get rid of the current on the top of everything play button and add a simple button "Transfer" on the right of the "Save" button.

**Comment by adityastic** [comment]
@mariobehling ok sir. That will be done
