### ISSUE TITLE
Add button "open folder" on top right of screen and delete "+" button (instead add "import" to saved configurations)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#236]
1. Please add button "open folder" on top right of screen. This button should direct people to "Saved Configurations"

2. Delete "+" button on the top right of the screen and instead add a button "import" to saved configurations.

3. Add a play button on each tile on the "Saved Config" screen to enable the user to see the saved badges.

4. Change "Saved Configurations" to "Saved Badges" in all views.

5. Delete bottom menu. There is no need for it.

**Comment by adityastic** [comment]
Hi Sir, I have some doubts regarding this issue. 
1. The button should redirect people to the "Saved Configuration" section or the place where the configuration are actually saved in the device

**Comment by mariobehling** [comment]
> The 3rd point where you want to add a play button which will then display the saved badge on the preview, currently we just press the tile and it displays it on the preview, so you want us to change that to a button right?. Correct me if there is some misunderstanding

Yes, this is not obvious enough. Instead of clicking on the entire thing, please add a play button. Also later we want to add more buttons here. So, the entire area should not be used for one function only. You can keep the color change.

**Comment by adityastic** [comment]
> > The 3rd point where you want to add a play button which will then display the saved badge on the preview, currently we just press the tile and it displays it on the preview, so you want us to change that to a button right?. Correct me if there is some misunderstanding
> 
> Yes, this is not obvious enough. Instead of clicking on the entire thing, please add a play button. Also later we want to add more buttons here. So, the entire area should not be used for one function only. You can keep the color change.

On It.

**Comment by adityastic** [comment]
@mariobehling please explain the interface of transferring the saved badges
