### ISSUE TITLE
Don't show bottom menu when showing the keyboard for text input.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#237]
Don't show bottom menu when showing the keyboard for text input.

**Comment by adityastic** [comment]
Got it

**Comment by mariobehling** [comment]
![Screenshot_2019-05-01-15-57-44-763_com nilhcem blenamebadge](https://user-images.githubusercontent.com/1583873/57009625-485d2180-6c2a-11e9-960a-39e433a79733.png)

**Comment by mariobehling** [comment]
Actually, just delete the bottom menu entirely. It is not needed. We will enable people to access it differently. See https://github.com/fossasia/badge-magic-android/issues/236

**Comment by adityastic** [comment]
@mariobehling got it

**Comment by yashk2000** [comment]
@mariobehling @iamareebjamal this issue has been resolved. The bottom bar has been completely removed.

**Comment by adityastic** [comment]
@yashk2000 oh yeah I guess I accidentally fixed this
