### ISSUE TITLE
Implement support for emoticons as part of "text" field and improve UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#238]
1. Text editors already have emoticons. Please implement full support for emoticons as part of the text.

2. Rename "Send Drawables" to "Clipart"

3. Rename "Send Text" to "Editor"

**Comment by adityastic** [comment]
@mariobehling Implementing Emoticons is not possible at this moment as our application need to have the hexadecimals strings of the emoji predefined. There are over 200+ emoji's, that would not be feasible. Instead there is a neat feature that I suggested in my GSoC Application which lets you include the drawables in the text field. This drawable section can have custom drawings as well. But To get to that point a lot of other things need to be created. There is no base for drawables as of now

**Comment by yashk2000** [comment]
@mariobehling since the badge is just 40x11, it will be very difficult to implement emojis. The expressions for all emojis might not be properly visible. I think that the solution proposed by @adityastic is a feasible one for this issue.

**Comment by mariobehling** [comment]
There are probably larger badges and badges that have a higher resolution in the near future. So, if we could support the most common emoticons it would be good already, e.g. the smileys. I also wonder if there is an option to restrict the on screen keyboard to only show the characters and emoticons that work.

**Comment by adityastic** [comment]
@mariobehling if in future we support the larger resolution badges, then definitely we can work on emoji's. As far as restricting keyboard goes, I'm not sure google allows us to restrict it to anything other than an inputtype filter

**Comment by yashk2000** [comment]
@adityastic we can create a custom soft keyboard, after all, there are many custom keyboard apps in the play store, but that will require lots of new XML files. Also, we will have to define a lot of functions to control how it works. I don't know how feasible this method will be though.

**Comment by adityastic** [comment]
Why not just create and save them inside the drawables itself, it is almost the same thing. Check the new layout suggested by @mariobehling in the last issue

**Comment by yashk2000** [comment]
Yes. That'll be the best option.

**Comment by mariobehling** [comment]
The name drawables is misleading. We need a way to import "cliparts" and render images into something that works on the badges. The current implementation of "cliparts" has a lot of limits. This is a different discussion. People are used to use their entire keyboard including emoticons. A simple smiley should already be possible with the current badge. More complicated emoticons can be simplified, but we can go step by step. First we need support for simple emoticons, e.g. a smiley in the text in put field.

**Comment by yashk2000** [comment]
@mariobehling sure. The simple emoticons can be implemented. We'll start with those first.

**Comment by adityastic** [comment]
@mariobehling ok sir, we will try to implement the basic emoticons for now.

**Comment by adityastic** [comment]
@mariobehling I guess this is solved. We can not have emoticons in the same text field
