### ISSUE TITLE
Implement Clipart (Drawables) dropdown area 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#240]
The Cliparts are currently movable to the right and left. Instead there should be an area below and in future the user should be able to add their own cliparts.

Some inspiration from Whatsapp:
![Screenshot from 2019-05-01 17-51-20](https://user-images.githubusercontent.com/1583873/57012599-f3c1a280-6c39-11e9-992d-ac83aa5d44cd.png)

**Comment by adityastic** [comment]
Yes Sir, This is exactly what I proposed in my proposal and also said in #238. I would love to implement this
