### ISSUE TITLE
Implement "Effects" in same way as "Animations"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#245]
Animations has been implemented with a boxes that show the animation immediately. Implement a section "Effects" below in the same way.

* Please take out the "colon" behind "Animations" as well. Don't add semicolons behind the section headings
* Also change "Send Drawables" to "Clipart" and "Send Text" to "Editor"

Screenshots for the change:
![issue232](https://user-images.githubusercontent.com/11988517/57059626-caedeb80-6cd3-11e9-9f14-980baeda1ed5.gif)

**Comment by adityastic** [comment]
Sure Sir, I would love to take this issue
