### ISSUE TITLE
Improve and Simplify UI and Colors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#248]
Please improve the UI as follows:

* Make sections Speed, Animations, Effects in a kind of sub tabs as in the mockup below
* Use one standard red in all areas (the same red as on the top menu bar) - also for the highlighted areas - use the same red!
* Delete "Text to Send"

![57098056-d3c3d900-6d36-11e9-8472-1ef7fe67b25c](https://user-images.githubusercontent.com/1583873/57120755-035dfa00-6da6-11e9-91c6-ccee5f4dedd8.gif)

**Comment by adityastic** [comment]
That is a great idea sir
