### ISSUE TITLE
Change UI to use Capital Letters only for first letter (avoid to capitalize all) and Increase space above Save/Transfer button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#250]
1. Please change the UI to use Capital Letters only for first letter (avoid to capitalize all).

2. Increase space above Save/Transfer button in all views. It is currently very close to the above area.

**Comment by adityastic** [comment]
Got it Sir

**Comment by adityastic** [comment]
@yashk2000 Can you Please solve this issue

**Comment by yashk2000** [comment]
@adityastic sure.

**Comment by mariobehling** [comment]
Reopening this issue as it is only partly fixed. Many areas in this app and buttons still have capitals only.

**Comment by yashk2000** [comment]
They are in the saved section mostly. I'll fix it right now.

**Comment by iamareebjamal** [comment]
@mariobehling It's standard in Android to have button text in caps by default.
