### ISSUE TITLE
Implement a Drawer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#251]
Please implement a drawer similar to PSLab Android with the following:
* Create Badge
* Saved Badges
* About Us
* Feedback/Bug Reports (Link to Issue Tracker https://github.com/fossasia/badge-magic-android/issues)
* Buy Badge (https://sg.pslab.io)

![view_navigation_drawer](https://user-images.githubusercontent.com/1583873/57126193-ac185380-6dbe-11e9-8f01-7e7d2238a581.png)

**Comment by adityastic** [comment]
Great Sir, Will do this with #236 by today

**Comment by adityastic** [comment]
@yashk2000, let's start working on it

**Comment by yashk2000** [comment]
@adityastic on it.
