### ISSUE TITLE
Sections are hidden behind save/transfer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#255]
Please avoid to implement different layers. The save/transfer buttons should be below the upper area (effects etc). Don't make it go on top. Keep it on the same layer.

![Screenshot_2019-05-03-23-33-47-267_com nilhcem blenamebadge](https://user-images.githubusercontent.com/1583873/57148614-8ad65800-6dfc-11e9-97c2-07532f8de4e5.png)

**Comment by adityastic** [comment]
I got the issue. Will fix it as soon as I come home, sorry for the inconvenience
