### ISSUE TITLE
Implement an about screen.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#259]
Implement an about screen as a first step use the info text from the Readme.md.

**Comment by adityastic** [comment]
Morning sir, would love to work on it

**Comment by adityastic** [comment]
@mariobehling Can you tell me the links you would like to add here.
![ss](https://user-images.githubusercontent.com/11988517/57173216-06122b00-6e4a-11e9-848f-00a2f5122b03.jpg)
