### ISSUE TITLE
Implement an Edit button for saved badges

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#261]
The badges on the saved badges screen are missing the option to edit them. Please implement it.

**Comment by adityastic** [comment]
@mariobehling So, when the user clicks on the edit button. The badge should be loaded in another activity where he can edit the badge?. Currently we cannot restore saved badge to its respective text or clipart, because the LED Badge works in bits, and we store the bits inside the badge.txt file. Please share your thoughts on it

**Comment by adityastic** [comment]
@mariobehling this can be implemented when we have a feature to create custom cliparts as we can then redirect the the user to the edit screen where he can edit the clipaet accordingly

**Comment by anhanh11001** [comment]
@mariobehling Can I work on this, I'm thinking of making two round button in the corner for edit and share, and making the swiping left and right for deletion. For editting, it will make a pop up dialog?

**Comment by adityastic** [comment]
@anhanh11001 how are you going to edit it?

**Comment by anhanh11001** [comment]
@adityastic for now, I'm thinking about a pop - up alert dialog with all of the setting info and then overwrite the current file. Do you think will there be any problems with that ?

**Comment by adityastic** [comment]
@anhanh11001 how are you going to restore the saved badge. It is stored in hexadecimal strings, not with text or drawableSelectedID

**Comment by anhanh11001** [comment]
I don't quite understand your question, because this issue is about editting, why do we want to discuss about restoring?

**Comment by adityastic** [comment]
@anhanh11001 How are you going to edit the badge, if you don't have a mechanism to read the badge. Example: I saved a custom clipart  💀 . then shared it with someone who does not has this clipart in his app. You can import, and transfer the unknown clipart to the hardware. But how will you be able to edit it to ☠️ ? if the person needs to change some parts in the clipart and we need to be able to read the unknown bytes stored inside the file

**Comment by anhanh11001** [comment]
ok, I kinda get your point now, at first I thought editing is more about to edit the setting of the badges (marque,inverted,speed,...). 

But what do you mean by "don't have a mechanism to read the badge". Because if a user doesn't have it then how can they load the information and run the animations with text/clipart?

One more thing, what do you mean by "having clipart 💀 and edit it to ☠️". That's basically changing new clipart, which can be done in the main fragment.

**Comment by adityastic** [comment]
By "don't have a mechanism to read the badge" I mean, you need to find a way read the byte code and create the text out of it. And if it is not a text, it will be a clipart. then you need to find out which one.

BUT, if you someone creates a custom clipart like this 💀 and saves it into his application, let's name the owner of this device as owner 1. owner 1 now shares the clipart to owner 2. Owner 2 can import the clipart using the file, even watch it on the preview because preview reads data in the form of bits and not in the form of text or drawable. when owner 2 clicks on edit, he should be taken back to the screen where he can edit the clipart, but as this clipart was created by owner 1 in his device you cannot identify it using some drawableID. 
Sorry for my bad english

**Comment by anhanh11001** [comment]
ok, it's clear to me know. Thank you for your detailed explanation! I will think more about the solution.

**Comment by iamareebjamal** [comment]
Why not save both source and hex and no need for reverse lookup

**Comment by adityastic** [comment]
@iamareebjamal if we save the drawable itself which is the source, and transfer the file. In the other person's application we still would have to look up which drawable it is matching and what if it was a custom clipart, the drawable would not match any of the stored cliparts or text

**Comment by iamareebjamal** [comment]
> we still would have to look up which drawable it is matching

Why? You already have the 8-bit source

**Comment by adityastic** [comment]
@iamareebjamal I did not get what you mean by 8-bit source sir. Can you please elaborate

**Comment by iamareebjamal** [comment]
By source of the drawable, I mean you have the information needed to show it on the screen

**Comment by adityastic** [comment]
@iamareebjamal I created 40x11 drawables by hand and saved them into the application, when a user selects it, we convert the drawable to a 16-bit number of variable length. The keyword here is variable length as the length of the 16-bit number depends upon the number of text which were used to create the text or the width of the drawable excluding the transparent pixels. This 16-bit variable length number is what is general for both text and drawable, this is the format which can be read by the preview and the hardware too. And we are storing this 16-bit variable length number itself currently.

**Comment by adityastic** [comment]
And if we want to convert the 16-bit number to it's respective text or drawable. We need to try every possible combination of our resources (text or drawable) and check which one matches it exactly if we want to edit the saved badge. Hence my suggestion is to create a section seperately which can let you edit any 16 bit number, but this will definitely take time sir

**Comment by adityastic** [comment]
@iamareebjamal I am even ready to work on it even but I have an exam tomorrow, please let me know your thoughts on it.

**Comment by adityastic** [comment]
@iamareebjamal I am even ready to work on it even but I have an exam tomorrow, please let me know your thoughts on it sir. This is one of the major issues who's solution is listed in my gsoc proposal as well

Sorry for my bad English

**Comment by iamareebjamal** [comment]
0001000
0010100
0100010
0010100
0001000

You have this as source, you can't show a diamond?

**Comment by adityastic** [comment]
How will you compare it to a drawable without converting every drawable inside the app and checking which drawable produces the same source ?

**Comment by adityastic** [comment]
And the source will be 102f882f10

**Comment by adityastic** [comment]
We are working with hexadecimals and not binary

**Comment by adityastic** [comment]
Now take this condition.
0001000000001000
0010100000001000
0100010000001000
0010100000001000
0001000000001000

Its hex will be 100f2f0f880f2f0f100f

**Comment by adityastic** [comment]
If you want to convert this to its original high level values which is a diamond image and line image. You will have to try every combination with the available images to get all the possible images which match the resource

**Comment by adityastic** [comment]
Now consider more than 5 images. 

we will have to test n to power n conditions where n is the number of possible text and drawables inside the application

**Comment by iamareebjamal** [comment]
You are not understanding what I mean by source. By source, I mean bitmap

**Comment by adityastic** [comment]
@iamareebjamal ok sir, I get it now so now if we save the source ( text or bitmap ) and the configuration in the badge file then we can bring it back to the original state. The only issue which would be there is if someone created a custom clipart and sent it to a device which does not have this clipart

**Comment by adityastic** [comment]
@iamareebjamal yes sir, actually this is an amazing idea. I guess I can pull this off in under a week. I just need to create a view which can interpret text and drawable at the same time. It will be able to store json in this format

{ "hexstrings":[{"type":"clipart", "bytes":"10fd1331..."}.....].... }

**Comment by adityastic** [comment]
Yes I can confirm that this is possible after #238 and #262. Thanks @iamareebjamal
