### ISSUE TITLE
Enable user to put in more than one Clipart

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#262]
Currently the user is only able to put in one clipart at a time. Please implement a "clipart" editing line (same as for text input) and enable the user to put in several cliparts.

![57173730-fac2fd80-6e51-11e9-8b62-8fe0ae9f5d92](https://user-images.githubusercontent.com/1583873/57173816-35d02b80-6e68-11e9-85e3-597382f55b4a.jpg)

**Comment by adityastic** [comment]
@mariobehling This is exactly what we talked about on gitter sir. Once the core code is added, we can have "Text <emoji>" or "<emoji> <emoji" or any combination you like. Making this core change would take around 2 weeks sir
