### ISSUE TITLE
App state not retained on rotating screen.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#267]
**Describe the bug**

When the app is rotated in the the about section, or saved badges section, the app enters edit mode. 

**To Reproduce**
Go to saved badges or about section. Rotate the screen. App goes into edit mode.

**Expected behavior**
App should stay in the fragment in which it was.

**Would you like to work on the issue?**

YES.

**Comment by anhanh11001** [comment]
I am working on that and I'm about to send a PR #147

**Comment by yashk2000** [comment]
Ok. Metion this issue to as fixed when the pr is finalized.

**Comment by anhanh11001** [comment]
yup!
