### ISSUE TITLE
Enable Text and Cliparts at the same time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#269]
If the user enters a text and then switches to clipart view, the text no longer appears on the batch.

Expected: The text should stay and cliparts should be added after the text. Both text and cliparts should appear on the batch screen.

**Comment by adityastic** [comment]
I would like to work on this

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal please check gitter

**Comment by adityastic** [comment]
@mariobehling close this, it is fixed
