### ISSUE TITLE
Decrease white space above top buttons, increase space above save/transfer, decrease space below save/transfer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#270]
The screen does not work entirely well on smaller phones yet. 

The app should be working on **smaller screens as well as on bigger screens without scrolling**.

Therefore please increase/decrease the spacing as follows. Ensure the UI feels/looks naturals. Avoid too small or too large white areas.

Change the following:
* decrease height of buttons
* decrease white space above top buttons
* increase space above save/transfer
* decrease space below save/transfer

![Screenshot_2019-05-07-00-07-23-997_com nilhcem blenamebadge](https://user-images.githubusercontent.com/1583873/57238720-a6d83480-705c-11e9-85a2-7d4b422283fa.png)

**Comment by adityastic** [comment]
@mariobehling Please Check Gitter

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling fixed in the last pr. please close
