### ISSUE TITLE
Implement more border options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#271]
The effect tab should offer more options for borders.

![Screenshot_2019-05-07-01-22-16-691_com nilhcem blenamebadge](https://user-images.githubusercontent.com/1583873/57242759-ef94eb00-7066-11e9-952e-9448f0a4e4a0.png)

**Comment by adityastic** [comment]
@mariobehling only the first two effects: flash and marquee are supported by the badge. Invert LED is an in-house solution developed by me, which is calculated on the app itself and then passed on to the device.

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal

**Comment by mariobehling** [comment]
Develop your own ideas.

**Comment by adityastic** [comment]
@mariobehling ok sir, let me think about what cool things I can create
