### ISSUE TITLE
Implement support for transfer over USB and WiFi

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#282]
Apart from the Bluetooth device there are devices that accept transfer of data over USB and WiFi. Please implement support of the app for these transfer methods.

**Comment by adityastic** [comment]
@mariobehling we need to have the device in hand to debug the bytes sent to the device. If you have something in mind, drop a link. I will look at that device

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal

**Comment by T-vK** [comment]
I'm also very much interested in this. Especially for the cheap ones:
https://www.aliexpress.com/item/32854131975.html
Tell me if I can assist in any way.

**Comment by adityastic** [comment]
@T-vK sure, please go ahead with the implementation

**Comment by ghost** [comment]
can i work on this issue?

**Comment by adityastic** [comment]
> can i work on this issue?

Sure, which badge or device are you planning to support?

**Comment by ghost** [comment]
> > can i work on this issue?
> 
> Sure, which badge or device are you planning to support?

LSLED

**Comment by adityastic** [comment]
> > > can i work on this issue?
> > 
> > Sure, which badge or device are you planning to support?
> 
> LSLED

Cool, go ahead!
