### ISSUE TITLE
Investigate and Support different Panel Sizes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#284]
Other apps like LED Art (https://play.google.com/store/apps/details?id=cn.huidu.huiduapp) support different panel sizes. Please add support for the same panel sizes.

![Screenshot_2019-05-13-12-22-13-684_cn huidu huiduapp](https://user-images.githubusercontent.com/1583873/57614891-a1a64880-757a-11e9-8e19-f0d0727e0125.png)

**Comment by adityastic** [comment]
@mariobehling We need to have the device in hand to support them, any suggestions?

**Comment by mariobehling** [comment]
Apart from access to devices, you could research the size of the panels, e.g. how many pixels they use and consider the implementation needed. The technology of the panels is probably similar.

**Comment by adityastic** [comment]
@mariobehling I will go out today to find out the possible led's and the ways to program it
