### ISSUE TITLE
Convert Icons to SVG

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#296]
Since Android 5 it is possible to use SVGs in Android. They are automatically converted to PNGs if necessary in Android Studio. Using SVGs will stop us worrying about resolutions and make it easier to keep the image quality high. Please change the icons to SVGs.

Reference: https://android.jlelse.eu/stop-using-your-svg-as-png-87b5edd367cd

**Comment by adityastic** [comment]
In Android in order to use .png, .jpg or any other bitmap resources we need to put it inside drawable directory
Reference: https://developer.android.com/guide/topics/resources/providing-resources
This is the standard in android

**Comment by adityastic** [comment]
Also all the images which could be converted to svg's or vector drawables are already converted. There are no icons left which need to be converted to svg as of now

**Comment by adityastic** [comment]
@mariobehling also all the images which can be converted to svg are already converted

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal Please Close this, all the possible icons are already in svg

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/badge-magic-android/tree/development/app/src/main/res/drawable-nodpi

I don't think so

**Comment by adityastic** [comment]
@iamareebjamal are you sure, the size wont increase?. The reason they are not converted is because if I do, there size may increase from bytes to kilobytes

**Comment by iamareebjamal** [comment]
> make it easier to keep the image quality high

Also, representing such simple icons will not take much size. And if it does, then something is wrong. png for this low resolution will have smaller size but it will not be scalable and consume a lot more than vector file in higher resolutions.

Also, it makes it easier to edit later

**Comment by adityastic** [comment]
@iamareebjamal the size of the images is currently in bytes. If you shift them to xml, it will increase rather decreasing. Just tested it out. Also the badge requires no longer than 40x11 images, converting them would increase the size rather than decreasing it

**Comment by iamareebjamal** [comment]
```
we can scale them perfectly fine in the app right now as well, as they are monochromatic and symmetric
```

All the more reason to make them SVG

```
the size of the images is currently in bytes. If you shift them to xml, it will increase rather decreasing
```

Doesn't matter, they are binary, unchangeable and non scalable. If I want to edit them, those bytes will be added to the repo again. In SVG, only changes I do as text will be stored

Not every issue is a discussion. This has to be done

**Comment by adityastic** [comment]
Got it
