### ISSUE TITLE
Fix issues and improve Saved Badges screen when no badges are saved

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#306]
Please change Saved Badges screen as follows, when no badges are saved:
* Ensure all design is showing on screen also for small screens
* Simplify smiley to one color using the design of a "Badge Smiley" instead of a full colored smiley

![Screenshot_2019-05-16-20-02-43-147_org fossasia badgemagic](https://user-images.githubusercontent.com/1583873/57876576-f4e7f780-7815-11e9-95dc-ed920d8af6ff.png)

**Comment by adityastic** [comment]
Ok sir
