### ISSUE TITLE
memory leak due to EditableInputConnection

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#316]
**Describe the bug**
memory leak due to EditableInputConnection

**Screenshots**
![nmmem](https://user-images.githubusercontent.com/11988517/58147785-c5a01300-7c79-11e9-8698-f4a39d27f50d.jpg)

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
@iamareebjamal let me know what do you plan to do with this issue

**Comment by akri16** [comment]
I don`t think this is solvable. It`s an internal Android framework bug. Please see this thread https://issuetracker.google.com/issues/37043700

There are workarounds though. Please refer to https://issuetracker.google.com/issues/37043700#comment17.
Should I implement it?

@adityastic @iamareebjamal @mariobehling

**Comment by adityastic** [comment]
> I don`t think this is solvable. It`s an internal Android framework bug. Please see this thread https://issuetracker.google.com/issues/37043700
> 
> There are workarounds though. Please refer to https://issuetracker.google.com/issues/37043700#comment17.
> Should I implement it?
> 
> @adityastic @iamareebjamal @mariobehling 

We can leave it as is, let's leave it to google to fix. Didn't cause any spike in leaks as well. Let me close it
