### ISSUE TITLE
Add badge for Badge Magic Play Store to Readme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#327]
Please add the badge and link to https://play.google.com/store/apps/details?id=org.fossasia.badgemagic

**Comment by adityastic** [comment]
@mariobehling can you explain me what to add to the store listing. As currently, the store listing has 'You can purchase a compatible LED Badge at https://sg.pslab.io' this

**Comment by yashk2000** [comment]
We have to add a play store badge in the readme. Check out this readme for [example](https://github.com/fossasia/phimpme-android). I'll add the badge.

**Comment by adityastic** [comment]
@yashk2000 oh ok I get it now.
