### ISSUE TITLE
Submit app to Fdroid

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#328]
The app is not on Fdroid yet. Please submit it and add an Fdroid badge to the Readme.

**Comment by adityastic** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/4894.

**Comment by CloudyPadmal** [comment]
@adityastic I think it would be better if you can replace 
```
AutoUpdateMode: None
UpdateCheckMode: Tags
```
part to something like
```
Auto Update Mode:Version v%v
Update Check Mode:Tags
Current Version:2.0.13
Current Version Code:14
```

So whenever we make a release with the correct labeling, it will deploy automatically.

**Comment by adityastic** [comment]
@CloudyPadmal I tried, https://gitlab.com/adityastic/fdroiddata/commit/85fb5e045e79612cb873bd1fc188ca0549b1904b but it failed to pass the lint.
Here is the list of pipelines : https://gitlab.com/fdroid/fdroiddata/merge_requests/4894/pipelines.

**Comment by iamareebjamal** [comment]
AFAIK, it is passed. Plese change the config as pointed out by @CloudyPadmal

**Comment by adityastic** [comment]
@iamareebjamal Sure

**Comment by iamareebjamal** [comment]
Please test it locally before pushing

**Comment by adityastic** [comment]
@iamareebjamal it passes the lint test locally. That's the reason It took so many pipelines for finalizing the merge request
