### ISSUE TITLE
Do not show emoticons always. Follow methods similar to messengers like whatsapp

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#339]
Currently the emoticons and text always cover the screen. Please change the features as follows:
* Portray a small emoticon or text button similar to Whatsapp on the left side of the editing field
* Show a button on the editor in blue (like before) to minimize the keyboard
* Don't allow multiple lines (as the actual device does not offer that feature!)

![Screenshot_2019-05-27-21-29-41-025_com whatsapp](https://user-images.githubusercontent.com/1583873/58436772-62720e80-80c7-11e9-993a-15dc053a268f.png)

**Comment by adityastic** [comment]
Sorry for being late, had some health issues. @mariobehling @iamareebjamal do you want this section to pop up like the keyboard or should I just toggle the visibility

**Comment by adityastic** [comment]
@mariobehling also I did not get what you mean by ' Show a button on the editor in blue (like before) ', because there was no button before. Please give me feedback on this as well

**Comment by mariobehling** [comment]
How can I get rid of showing the text editor? Before there was a button in blue. Now the only option is to press the back button. No-one understands that. We need a simple way to hide the text screen editor - the keyboard. Please check out how chat apps are doing it. We don't want to always show the keyboard.

**Comment by adityastic** [comment]
@mariobehling I get your point, I can make it work. It's related with the inputmethod

**Comment by adityastic** [comment]
@mariobehling Im afraid, it is a keyboard specific feature. Most of the keyboards dont support it because of the on screen buttons. The Back On Screen Button is morphed into a Down button when keyboard is being used to indicate that you can close your keyboard using that button.
