### ISSUE TITLE
Enhance Emoticon/Text Icon Editor Choice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#354]
The icon for emoticons looks different to what people are used to in Whatsapp etc. Please use a smiley to show the emoticon options and use a keyboard symbol to switch to text editing. Please compare to Whatsapp.

<img width="547" alt="Screenshot 2019-06-07 at 3 15 54 PM" src="https://user-images.githubusercontent.com/11988517/59095923-50019b80-8937-11e9-8ef4-79f3ba3c008a.png">

![nexus2cee_whatsapp-material-8](https://user-images.githubusercontent.com/1583873/59108802-0c5d6080-893c-11e9-8614-a539bd97ee2c.png)

**Comment by adityastic** [comment]
ok sir
