### ISSUE TITLE
Only allow oneliners

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#355]
In the latest version the editor suddenly permits multi-line editing. The current devices don't have this feature. Please only allow one line.

**Comment by adityastic** [comment]
@mariobehling can you show me how does multiline editor looks for you. I am not able to confirm this issue, it shows as single line to me. Please send me a screenshot for the same

**Comment by mariobehling** [comment]
By clicking "enter" it suddenly goes to two lines.
