### ISSUE TITLE
Implement a drawing mode

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#357]
Implement a mode where the user can draw on the screen and create their own badge art.

1. Drawing mode should show the badge area in full in horizontal position.
2. The user can draw on the screen. There should be two functions
  a) draw (the user highlights anything s/he touches on the screen)
  b) delete (the user "unlights" anything s/he touches on the screen)

**Comment by adityastic** [comment]
Great, this is very interesting
