### ISSUE TITLE
Morphing Issues with Preview Badge

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#370]
**Describe the bug**
morphing issues with preview badge

<img width="420" alt="Screenshot 2019-06-13 at 9 19 20 AM" src="https://user-images.githubusercontent.com/11988517/59402537-62a72500-8dbc-11e9-8d55-1b8f60a956f7.png">

**Would you like to work on the issue?**
YES

**Comment by mariobehling** [comment]
What is the exact issue? Please describe the problem.

**Comment by adityastic** [comment]
The preview badge will cut from the edges when you use the preview badge with other layouts

**Comment by adityastic** [comment]
@mariobehling I've added an image check the layout when I applied margin to it. The Algorithm did not take all the conditions into consideration yet. We need to maintain it, because we cannot know these changes before hand for every condition possible

**Comment by mariobehling** [comment]
Ok, thank you.
