### ISSUE TITLE
Implement animation where every character or letter is added step by step

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#372]
Please implement the animation to show every letter/character getting added one by one. When the badge is full show the next letters starting at the front of the screen.

**Comment by adityastic** [comment]
Hey Mario. We cannot create our own animations as of now, the device only understands the animations we currently have. But I have a plan to make this happen, using the feature inside the badge which allows you to send 8 badge config to the device and it plays them one by one. Can we please implement that first and then move forward with this
