### ISSUE TITLE
Add fan LED as additional device

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#373]
There are a number of FAN LEDs on the market. Please add support for more fan LEDs to the app, e.g. as in these apps:
* https://play.google.com/store/apps/details?id=com.usb.mpfan
* https://play.google.com/store/apps/details?id=com.molink.Brain.Z3Lan
* https://play.google.com/store/apps/details?id=com.molink.Brain.Z3
* https://play.google.com/store/apps/details?id=com.ihunuo.fanforbrookstone
* https://play.google.com/store/apps/details?id=com.fsp.FanDisplay
* https://play.google.com/store/apps/details?id=com.player.adplayer2
* https://play.google.com/store/apps/details?id=com.ihunuo.rgbfontflashfan

**Comment by adityastic** [comment]
Great Let me investigate more about these fans
