### ISSUE TITLE
Use Data Binding

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#375]
Use Data Binding with ViewModels

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling add this to next week's milestone

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling add this to next week's milestone

**Comment by iamareebjamal** [comment]
Is this done or ignored?

**Comment by adityastic** [comment]
@iamareebjamal the rest of the activities I was planning to add data binding to have adapters linked to the viewmodel. If I move forward, it will make the project fairly complex for people who are starting to understand this project, that's why I closed this issue
