### ISSUE TITLE
Add Screenshots to Fdroid

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#402]
Fdroid listing does not have any screenshots of the app. Please add it: https://f-droid.org/en/packages/org.fossasia.badgemagic/

**Comment by adityastic** [comment]
Merge Request Submitted : https://gitlab.com/fdroid/fdroiddata/merge_requests/4973

**Comment by adityastic** [comment]
Update: We need to include the screenshot in the app's repo. @iamareebjamal plz check https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository . It has an option for fastlane supply, please guide me how can I include the screenshots

**Comment by iamareebjamal** [comment]
Follow the guide

**Comment by mariobehling** [comment]
This issue is not solved.

**Comment by adityastic** [comment]
@mariobehling the screenshots get updated when we release a new build. We did not release a new build yet. As soon as we release a new version, fdroid will build the next release on their repo and add the screenshots

**Comment by adityastic** [comment]
https://f-droid.org/en/packages/org.fossasia.badgemagic/ . Screenshots are updated xD
