### ISSUE TITLE
prepare gh-pages

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#410]
**Describe the feature you'd like**
gh pages for badge magic

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling wants me to generate gh-pages using travis. Can you help me out on what needs to be done, I'm not able to understand what needs to be done exactly. Any reference would be helpful. Thanks

**Comment by iamareebjamal** [comment]
I suppose he wants yaydoc to build them https://dev.yaydoc.org/

**Comment by adityastic** [comment]
@iamareebjamal http://yaydoc.org/ does not seem to work.

**Comment by adityastic** [comment]
@iamareebjamal any updates on what is the motive behind pushing gh pages from travis?. After researching about it seems that it is useful only when you want to keep the api documentation updated. I cannot find anything related to a project website being updated other than keeping the latest app upto date in the website

**Comment by iamareebjamal** [comment]
No idea

**Comment by adityastic** [comment]
@mariobehling please enlighten me about the use case
