### ISSUE TITLE
Bluetooth automatically turned off when switching to Draw fragment.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#413]
**Describe the bug**
When user shifts to Draw fragment, bluetooth is automatically turned off.

**To Reproduce**
Keep bluetooth on and shift to draw fragment. Bluetooth turns off.

**Expected behavior**
Bluetooth should not turn off automatically.

**Would you like to work on the issue?**

NO.

**Comment by yashk2000** [comment]
@adityastic could you please confirm if this issue is faced by you too?

**Comment by adityastic** [comment]
Yes, good job

**Comment by yashk2000** [comment]
@adityastic currently, Bluetooth is disabled whenever `onDestroy` is called. Should I remove `disableBluetooth()` from `onDestroy()`? 
The user might not want to disable Bluetooth every time the app is closed.

**Comment by adityastic** [comment]
@yashk2000 yes better

**Comment by yashk2000** [comment]
@adityastic ok. On it :+1:
