### ISSUE TITLE
Badge Magic v1.2.0 - Application suddenly stops when saving "Badge"

### ISSUE THREAD

**Issue by ammarraisafti** [fossasia/badge-magic-android#416]
# Actual behaviour
It should, though I don't allow applications to access location and storage on the device when starting the application.  This behavior will not stop the application when I save "Badge".

<code>According to my analysis, while storing "badge", the application must request back permission to access the location and storage on the device.</code>

# Expected behaviour
This application suddenly stopped when I saved "Badge". Because before I did not allow applications to access location and storage on the device.

# Step to reproduce
- Install and open the application

- Select "Deny" when the application requests permission to access location and storage.

- Enter teks, Swipe right, select animation "Right". Then click "Save". 

- Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite 
- Android version: 8.1.0
- Application version: 1.2.0

# Recording of the bug
https://youtu.be/BPnKGwYzZxI

**Comment by adityastic** [comment]
Thank you so much for reporting.
