### ISSUE TITLE
Indication should be shown if no device is found after scanning.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#42]
**Describe the feature you'd like**
An indication in form of a Toast message should be shown if no message is shown after scanning is done.

**Would you like to work on the issue?**
Yes.

**Comment by yatri1609** [comment]
@mariobehling @cweitat  I would like to send a PR for this can I ? As there is no response on the other PR proposed for this

**Comment by yashk2000** [comment]
@yatri1609 you are right, there is no response on the other pr for this. But I am working on it. I am a bit busy this week but I'll send a pr for this soon.
