### ISSUE TITLE
Update apk names and take out not needed ones

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#421]
The following APKs are not essential. Please take them out of the generation:

* badge-magic-master-app-release-unaligned.apk	
* badge-magic-dev-app-release-unsigned.apk

Further take out the word "app" from all APK names, e.g.
badge-magic-dev-debug.apk instead of badge-magic-dev-app-debug.apk.

**Comment by adityastic** [comment]
Done

**Comment by iamareebjamal** [comment]
Done where?

**Comment by adityastic** [comment]
@iamareebjamal done as in, will be done
