### ISSUE TITLE
(Badge Magic) [Version 1.2.0] The application crashes when I use Draw Clipart option and draws some application crashes.

### ISSUE THREAD

**Issue by XAMIR555** [fossasia/badge-magic-android#423]
#### Project Information
* Repository-----------:[Here](https://github.com/fossasia/badge-magic-android)
* Project Name---------: [Badge Magic ](https://play.google.com/store/apps/details?id=org.fossasia.badgemagic&ah=dWLy7rQKg16yxp3OLlfGsqjnp8c)
* Publisher------------: [FOSSASIA](https://github.com/fossasia)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
When I use the Draw Clipart option, try to draw some more, so do not crash the application. Whatever you draw, it should be easily drawn.

#### Actual behavior
The application crashes when I use Draw Clipart option and draws some application crashes.

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=org.fossasia.badgemagic&ah=dWLy7rQKg16yxp3OLlfGsqjnp8c)and open the application
* At the top left click 3 vertical dots
* click on Draw Clipart
* select the Draw option and try to draw some
* Note the Bug

* Browser/App version-:1.2.0
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190701_210715](https://user-images.githubusercontent.com/49812927/60481112-e710f900-9c40-11e9-9745-e5df27fbe3f8.gif)

# Logcat

<pre><code>07-01 21:04:19.266 13394 13394 E AndroidRuntime: FATAL EXCEPTION: main
07-01 21:04:19.266 13394 13394 E AndroidRuntime: Process: org.fossasia.badgemagic, PID: 13394
07-01 21:04:19.266 13394 13394 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at java.util.ArrayList.set(ArrayList.java:453)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at org.fossasia.badgemagic.ui.custom.DrawBadgeLayout.a(Unknown Source:163)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at org.fossasia.badgemagic.ui.custom.DrawBadgeLayout.onTouchEvent(Unknown Source:23)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:13471)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:731)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at b.a.d.j.dispatchTouchEvent(Unknown Source:2)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at b.a.d.j.dispatchTouchEvent(Unknown Source:2)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:689)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:13719)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6150)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5928)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5430)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5396)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5555)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5404)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5612)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5430)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5396)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5404)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8437)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8370)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8323)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8552)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8511)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8579)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:690)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-01 21:04:19.266 13394 13394 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: FATAL EXCEPTION: main
07-01 21:05:21.396 14398 14398 E AndroidRuntime: Process: org.fossasia.badgemagic, PID: 14398
07-01 21:05:21.396 14398 14398 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at java.util.ArrayList.set(ArrayList.java:453)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at org.fossasia.badgemagic.ui.custom.DrawBadgeLayout.a(Unknown Source:163)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at org.fossasia.badgemagic.ui.custom.DrawBadgeLayout.onTouchEvent(Unknown Source:23)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:13471)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:731)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at b.a.d.j.dispatchTouchEvent(Unknown Source:2)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at b.a.d.j.dispatchTouchEvent(Unknown Source:2)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:689)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:13719)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6150)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5928)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5430)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5396)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5555)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5404)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5612)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5430)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5396)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5404)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5377)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8437)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8370)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8323)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8552)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8511)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8579)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:690)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-01 21:05:21.396 14398 14398 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
</code></pre>

**Comment by adityastic** [comment]
@yashk2000 please confirm this error

**Comment by adityastic** [comment]
@XAMIR555 please specify the device as well

**Comment by XAMIR555** [comment]
@yashk2000  my devices samsung A20 android version 9.0.0

**Comment by XAMIR555** [comment]
![20190702_084938](https://user-images.githubusercontent.com/49812927/60482597-06128980-9c47-11e9-9c80-b93486c7f299.gif)

**Comment by XAMIR555** [comment]
![Screenshot_20190702-092431_Settings](https://user-images.githubusercontent.com/49812927/60482851-fe071980-9c47-11e9-8745-78fb662b0e03.jpg)

**Comment by adityastic** [comment]
@XAMIR555 thanks. I personally tested it on the S9+ and it does work for me. Let's see what @yashk2000 comes up with

**Comment by yashk2000** [comment]
It works for me too. I tried it in a Nokia 7 Plus, Android 9.

**Comment by XAMIR555** [comment]
@adityastic  welcome sir

**Comment by XAMIR555** [comment]
@yashk2000  some time work fine and many time app crashing on my devices

**Comment by XAMIR555** [comment]
@yashk2000  and i don,t know what is  problem because  i am zero knowledge about programing

**Comment by adityastic** [comment]
@XAMIR555 no issues sir, You've done a great job reporting this issue. This will be fixed very soon. Sorry for any inconvenience caused

**Comment by XAMIR555** [comment]
@adityastic  thanks you sir for your feedback

**Comment by adityastic** [comment]
@XAMIR555 Please check the debug application here https://github.com/fossasia/badge-magic-android/pull/424

**Comment by XAMIR555** [comment]
@adityastic  just a minute i check and give you repose

**Comment by XAMIR555** [comment]
@adityastic  thanks you sir Bug has been fixed now

![20190702_102526](https://user-images.githubusercontent.com/49812927/60484692-483fc900-9c4f-11e9-935e-31a4eb4354f2.gif)

**Comment by yashk2000** [comment]
@XAMIR555 great. Thanks for reporting the bug :+1:

**Comment by adityastic** [comment]
@XAMIR555 Great. Please keep reporting issues, we are open to your feedbacks as well :). Glad it is resolved now. You Should receive the official update on playstore this weekend

**Comment by XAMIR555** [comment]
great sir nice to meet you
