### ISSUE TITLE
Updating issue templates.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#43]
**Describe the chore**
An option of yes or no should be provided in the issue templates.

![screenshot from 2019-03-05 16-47-50](https://user-images.githubusercontent.com/41234408/53801966-9d502480-3f66-11e9-8aa0-bbf2469b321b.png)

**Would you like to work on the issue?**
YES.

**Comment by mariobehling** [comment]
no priority at the moment.
