### ISSUE TITLE
Text in edit screen disappears on turning phone to widescreen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#431]
When I edit the screen and I turn the phone the text disappears.

**Comment by adityastic** [comment]
@yashk2000 confirm this for me plz

**Comment by yashk2000** [comment]
@adityastic the text in the edit text disappears on orientation change.

**Comment by adityastic** [comment]
> @adityastic the text in the edit text disappears on orientation change.

In the Create Badge Section?

**Comment by yashk2000** [comment]
Yes.
