### ISSUE TITLE
App deployment failing

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badge-magic-android#436]
https://github.com/fossasia/badge-magic-android/commit/4b37592625ba07daa6b9b0812bbfcfdf4cf40f9d#diff-f6341c962b5244e071d20a184d619bc7R71

@adityastic Why did you change ../scripts/fastlane.json to fastlane.json?

The app deployment is failing. Please fix ASAP

**Comment by adityastic** [comment]
@iamareebjamal I was out this weekend. I just got back. Had no internet connection. Do you want me to take this over?

**Comment by iamareebjamal** [comment]
Already fixed it
