### ISSUE TITLE
Add changes to fdroid metadata

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badge-magic-android#442]
Latest changes are not compatible with fdroid build server, please add these to the fdroid metadata

https://gitlab.com/fdroid/fdroiddata/merge_requests/5053/diffs

https://gitlab.com/fdroid/fdroiddata/merge_requests/5055/diffs

**Comment by adityastic** [comment]
@iamareebjamal badge magic was originally proposed as a yml. so https://gitlab.com/fdroid/fdroiddata/merge_requests/5055/diffs would not be required.

**Comment by iamareebjamal** [comment]
Take a look at the change carefully https://gitlab.com/fdroid/fdroiddata/merge_requests/5053/diffs#b3d66a210e9933feb51453da225fbb5d9b3992c1_55_55

**Comment by iamareebjamal** [comment]
I have given the second link as a reference to what the latest yml after changes will look like

**Comment by adityastic** [comment]
Great, should be done in some time

**Comment by adityastic** [comment]
Merged :)
