### ISSUE TITLE
Support Multicolored LED badges

### ISSUE THREAD

**Issue by lanrat** [fossasia/badge-magic-android#460]
**Describe the feature you'd like**
Some LED badges support more than one color, it would be awesome if this app supported that!

example: https://smile.amazon.com/VBLab-Upgraded-Wireless-Bluetooth-Rechargeable/dp/B07S1DVJH4/

**Comment by adityastic** [comment]
@mariobehling your thoughts on this?

**Comment by mariobehling** [comment]
The LED colors are not changeable. It is just a different color of the LED lights. This is the same thing as what we have. The app of the seller is not good: https://play.google.com/store/apps/details?id=com.yannis.ledcard&hl=en_US

It would be great to really have LEDs that can show different colors, but this is currently not the case. Closing it therefore.

**Comment by lanrat** [comment]
You appear to be correct that the LEDS are different individual colors, however the app you linked to is not compatible with that device. Instead it uses the CoolLED1248 app. See the discussion in #85.
