### ISSUE TITLE
Turning screen from vertical to horizontal direction deletes entered text/data for badge

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#467]
When the user turns their phone the text/data in the enter field is disappears.

**Comment by adityastic** [comment]
This is fixed as I remember. It must not be updated on playstore. lets release a version on playstore to get this updated. Confirmation video with the latest dev build:
https://drive.google.com/open?id=1-InJcZNEzNTVNQ2M5qFOZ3MCIk5DOgiV
