### ISSUE TITLE
Improve and Fix Saved Badge: Editing saved badge open edit cliparts editor and popup alternative

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#478]
1. Saved badge should be edited through the badge edit screen
2. Turning screen of saved badges to horizontal mode suddenly switches the app screen to edit badges mode
3. The popup functions "Perform Operation" should be included on the badge tab itself instead of in the popup. Please make changes as follows:
* Change "Share" to "Export" and open screen to "Save Item" instead of "Share Item"
* Show an "Export icon" on the badge tab itself
* Show a "Delete Icon" on the badge tab that deletes the badge
* Show a "Transfer Icon" on the badge tab that deletes the badge

![Screenshot_20190819_090836_org fossasia badgemagic](https://user-images.githubusercontent.com/1583873/63246104-2b447100-c262-11e9-8f05-09e378a670a5.jpg)

**Comment by refactor-droidyy** [comment]
@adityastic can I work on this?

**Comment by adityastic** [comment]
@refactor-droidyy sure. Please check the app log first. So we can release the application first

**Comment by marisasrida01** [comment]
nice

**Comment by refactor-droidyy** [comment]
@adityastic the changes regarding perform the operation as mentioned in issue should be like this please confirm.

![oie_2rIAwbSJwtE6](https://user-images.githubusercontent.com/44283521/71622602-e0b60680-2bfc-11ea-9864-89e8d4c6ccae.png)

**Comment by adityastic** [comment]
@refactor-droidyy yes that looks good to me
