### ISSUE TITLE
Edit Badge Screen / Edit Clipart Screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#479]
1. Add an "Open Folder" icon to the edit badge screen on the top right of the screen on the menu bar. The icon should open "Saved Badges".
1. Add an "Open Folder" icon to the edit clipart screen on the top right of the screen on the menu bar. The icon should open "Saved Cliparts".

**Comment by refactor-droidyy** [comment]
@mariobehling can i work on this issue ?

**Comment by adityastic** [comment]
@refactor-droidyy go ahead

**Comment by refactor-droidyy** [comment]
@adityastic open folder icon is not showing  instead of using oncreateoptionmenu and onoptionItemselected in the edit badge and edit clipart files can u help

**Comment by adityastic** [comment]
@refactor-droidyy I'm sorry, didn't get what you meant. I'd love to help
