### ISSUE TITLE
Use AndroidX artifacts

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/badge-magic-android#48]
**Describe the chore**
Migrate to androidX artifacts.
this means we don't have to use same support library version for all support libraries. Every support or better to say AndroidX library will maintain its own versioning . Maintaining support versions could be huge issues in the long run.

**Would you like to work on the issue?**
 Yes

**Comment by mariobehling** [comment]
Low priority. Please focus on moving forward the app through features first:
https://github.com/fossasia/badge-magic-android/labels/Priority%3A%20High
