### ISSUE TITLE
Readme.md: Add screenshots to /docs/images and add them into the Readme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#486]
The Readme.md currently contains screenshots from the Fastlane deployment. All documentation for the project itself should be using the /docs folder. Please **add the screenshots** to /docs/images and link those screenshots instead.

**Comment by iamareebjamal** [comment]
Can't change that. F-Droid and play store screenshot upload will fail

**Comment by mariobehling** [comment]
@iamareebjamal It is ok to duplicate images. The docs folder should be self-contained just like in other projects. Please duplicate the images. Don't try symlinks or something. Just add images into the docs/image folder itself please. If we use auto-generation of the docs it also fails. Let's keep our options simple and ready for auto-building documentation. Thanks

**Comment by mariobehling** [comment]
Don't use fastlane folder images for the Readme.md. Please always use everything in the /docs folder only for documentation.

**Comment by iamareebjamal** [comment]
But then we'll have the same problems as other repositories are having. The size will increase without any reason. Even now, the images and the deleted ones contribute to 80% of the repo size. And in the future as well new images will monotonically increase the size of repo beyond control. The solution will be to continuously clean git history which is not only a cumbersome process, but results in having to reclone the project everywhere

**Comment by iamareebjamal** [comment]
When building docs, we can add a command to copy the images in correct folder. Adding binary files in git repos lead to several problems which Phimp.me faced and PSLab is facing. Duplicating will also add to cognitive load where people will add the image in one place and forget to add/delete/modify it in another

**Comment by mariobehling** [comment]
@iamareebjamal I am not sure if this is over-engineering. These will not make up a lot of space even over time. These images are usually very small and we had problems in the past, because images are not in the docs folder, but somewhere else. This is still the case today with phimp.me. We want to generate automatic builds of websites from the docs folder as soon as possible again. Better keep it simple. It will not get bloated like in other projects and if we really want we could also delete it from the history.

![Screenshot from 2019-09-03 15-44-43](https://user-images.githubusercontent.com/1583873/64178537-ee7f9900-ce61-11e9-83c6-6811ebd70bf6.png)
We don't have a lot of engineers who understand all the details in our projects. Therefore keeping it simple will save us time. We should not spend too much time for discussing about just a few MB.

**Comment by iamareebjamal** [comment]
@adityastic Please move the files in docs folder and copy when uploading to fastlane

**Comment by adityastic** [comment]
@iamareebjamal got it, working on it
