### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [fossasia/badge-magic-android#499]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by yashk2000** [comment]
@leela52452 we do maintain a changelog [here](https://github.com/fossasia/badge-magic-android/releases). It is updated after every release.

**Comment by leela52452** [comment]
@yashk2000 oh.... it is part of release. hmm...
i was expecting in a separate file, helps me understand the direction and progress of project over a period of time.
something is better than nothing.

**Comment by yashk2000** [comment]
> i was expecting in a separate file, helps me understand the direction and progress of project over a period of time.

You can see changes for all the releases. From the beginning till now.
