### ISSUE TITLE
build deploy issue in forks

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#500]
**Describe the issue**
the deploy section in travis executes on forks, we should only execute it when we work on our repo

**Would you like to work on the issue?**
NO

**Comment by Zyro9922** [comment]
Can you guide me on how to go about solving this? I want to work on it.

**Comment by adityastic** [comment]
@Zyro9922 sure, you need to read about the deploy conditions used in travis and add our repo as a condition

**Comment by adityastic** [comment]
@Zyro9922 any updates?
