### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by www-asics-ws** [fossasia/badge-magic-android#507]
Guys, where are the "Getting Started" instructions. When I try to connect to the display via Bluetooth, I get an error on my android phone: 

![20191002_195419](https://user-images.githubusercontent.com/32382768/66046195-759e5a80-e54f-11e9-9b2a-3a67b9f3c25f.jpg)

**Comment by adityastic** [comment]
@www-asics-ws you don't have to pair a ble to send data to it
