### ISSUE TITLE
Unicode not working - non Latin languages not supported

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#517]
Currently we cannot see non-latin characters displayed on the badge. Please add support for Unicode.

![Screenshot_20191013_175442_org fossasia badgemagic](https://user-images.githubusercontent.com/1583873/66714612-d432c680-ede2-11e9-8550-2681862c5417.jpg)

**Comment by refactor-droidyy** [comment]
@mariobehling can i work on this issue

**Comment by adityastic** [comment]
@refactor-droidyy go ahead
