### ISSUE TITLE
About section for the app.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#52]
**Describe the chore**

There is no About or FAQS section in the app to describe it in detail which is present in most other apps.

**Would you like to work on the issue?**
YES.

@iamareebjamal @CloudyPadmal should I go ahead with this?

**Comment by yashk2000** [comment]
@iamareebjamal  could you please tell me if an About section should be added to the app?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
Low priority. Please focus on moving forward the app through features first:
https://github.com/fossasia/badge-magic-android/labels/Priority%3A%20High
