### ISSUE TITLE
Typing erors in README

### ISSUE THREAD

**Issue by Rajchowdhury420** [fossasia/badge-magic-android#530]
**Describe the chore**
There are some minor typing mistakes in README

line 1  :- Security in Bluetooth LE devices is optional, and many cheap products you can find on the market are not secured at all

line 2 :- As we understand how the Bluetooth LED badge works, converting a text to multiple byte arrays

**Would you like to work on the issue?**
Sure !

**Comment by adityastic** [comment]
@Rajchowdhury420 please point the typos in the readme to get complete information on the issue
