### ISSUE TITLE
Shift to App Specific Directory for storing Badge and Clipart's

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#544]
**Describe the bug**
We are currently using the external storage to save badges and clipart's. Lets change the directory to app specific external storage.

**Additional context**
Change the current directory from External Storage to App Specific directory.

**Comment by adityastic** [comment]
@refactor-droidyy would you like to work on it? Hint: All the File Storage is handled in StorageUtils

**Comment by refactor-droidyy** [comment]
@adityastic yes I will

**Comment by adityastic** [comment]
@refactor-droidyy let me know if you need help with anything. Good Luck 👍
