### ISSUE TITLE
Implement a Splash Screen

### ISSUE THREAD

**Issue by ark786** [fossasia/badge-magic-android#55]
**Describe the feature you'd like**
 A splash screen to improve look and feel of app 

**Screenshots**

![device-2019-03-17-033829](https://user-images.githubusercontent.com/28945306/54485036-e4f47b80-4897-11e9-8714-8296797b28a4.png)

**Would you like to work on the issue?**
yes :)

**Comment by AkashM398** [comment]
Yes I am working on this :)

**Comment by yashk2000** [comment]
@AkashM398 you cannot work on this before asking the creator of the issue. If the creator says that the issue is idle, then work on it, but not before. Please ask @ark786 before you start working on it.

**Comment by AkashM398** [comment]
okay, but how do I contact him?

**Comment by ark786** [comment]
@AkashM398 sorry but I was already working on the issue . Please open a new issue :)

**Comment by yashk2000** [comment]
@ark786 I think that splash screen is not needed. It is needed for apps that require some data to be loaded before being displayed to the user. So while the data is being loaded, the splash screen is displayed. But this app does not require any data to be loaded. Hence I think that the splash screen will be more of a hindrance.

**Comment by ark786** [comment]
@yashk2000  this is a valid point . Let's close this issue :)
