### ISSUE TITLE
Backpress Button to exit App

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/badge-magic-android#550]
**Describe the bug**
As you press the back button when you are in MainScreen i.e (Create Badge) the app closes .

**Expected behaviour**
A Toast Message("Press Back Again To Exit") Should appear if the back button is pressed(May be Accidentally pressed by user).
On double-clicking, within 2 seconds the app should close.

![before](https://user-images.githubusercontent.com/44283521/70850931-ba326480-1eb5-11ea-897f-88750a7bcbde.gif)

**Comment by refactor-droidyy** [comment]
@adityastic I want to work on this.

**Comment by adityastic** [comment]
@refactor-droidyy sure go ahead

**Comment by iamareebjamal** [comment]
This is a non standard behaviour and not recommended

**Comment by adityastic** [comment]
@refactor-droidyy we should not do it then
