### ISSUE TITLE
No Redirection after saving the drawn clipart

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/badge-magic-android#554]
**Describe the feature you'd like**

 When a user on draw clipart screen after saving the clipart the toast appears only. user should be redirected to saved clipart screen too. it is working like this  ->

![saveclipart](https://user-images.githubusercontent.com/44283521/70852802-bf021300-1ecb-11ea-907c-d3fd9afb9e8f.gif)

**It should work like this ->**
![clipartsavedsuccesly](https://user-images.githubusercontent.com/44283521/70852785-9843dc80-1ecb-11ea-9391-4fd9dbe41023.gif)

**Comment by refactor-droidyy** [comment]
@adityastic @iamareebjamal is this issue appropriate can i work on this?

**Comment by adityastic** [comment]
What if I want to draw more cliparts at the same time xD
