### ISSUE TITLE
Pre-Launch report for app v1.6.0

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badge-magic-android#556]
![image](https://user-images.githubusercontent.com/3874064/70852977-038eae00-1ece-11ea-87e0-aeaa16faf933.png)

Crashes

```
java.lang.IllegalStateException: Fragment e{62b7de9 (cd6fab0c-8891-4b60-8616-00b77da70617)} not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java)
	at org.fossasia.badgemagic.ui.fragments.SettingsFragment$onViewCreated$1$1.onClick(SettingsFragment.java)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
```

https://storage.googleapis.com/play-mtaas-results-prod/org.fossasia.badgemagic/8/sailfish-25-de_DE-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1576961476&Signature=kdVxYCOgmzXzHXiCF%2B%2Bb%2BRCi3FZ2koPIrOMJUW/hHM%2B65YzqTdrxM6BH1pd14Joet2SMtCO608ENpu/n%2Bw22Nu5YLNwTamaNsec5/mqUAj9k%2BXsJNZIqalOMDTOtd2L%2Bo2TXkqQu3x6LB140yhSaSTi5c0kBCP%2B%2BkSAHKRR3UPEP9PnBFupq%2B7ihMLFVicV2ipo/KNk9mgpqcRLvEuOKLv1wH8XGflWHzGB6B5nexzvBKo%2BwpXNDmEwIV%2BmKg/va6avIEn%2BIXcoykUkElw6/l8%2B82V5qe0LyZ/8G8cKDXn9K9vhi%2B4X%2BY5rIY5LOnCuaTuOHJb/RfYJBboeiP4oziw%3D%3D

```
java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(EmptyList.java)
	at kotlin.collections.EmptyList.get(EmptyList.java)
	at org.fossasia.badgemagic.viewmodels.SavedClipartViewModel.deleteClipart(SavedClipartViewModel.java)
	at org.fossasia.badgemagic.adapter.SavedClipartsAdapter$onBindViewHolder$1.onClick(SavedClipartsAdapter.java)
	at android.view.View.performClick(View.java:5612)
```

https://storage.googleapis.com/play-mtaas-results-prod/org.fossasia.badgemagic/8/griffin-24-en_IN-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1576961504&Signature=c6GnIbPh6zcM76ujkCLb30NI6MIKcIU4LCsIyTDEqukIvap710xUIAghPiI8JI3LQwCfEYIbx8WY9SDQEo89LmQ1PtGhmAMIn67YEVxUWQyCyd0gdbqCgf5ZzjUqlpzpQthEAPS1atKZ4lwZ/PArh7oobsmGQD%2BrfP9ntHt0%2Bp0ZOCP8bVQKGEprBGvngAHTpMp%2BS4TC92kuCxFG6rzuJXJsEv6svRMxkIrD6C0Za/VbRZ7eYrv8hYsVwha9LEmc50O2zYEyqCHqTmMFBSmM3nMEL7ajVnQXW6pqyu/c5EQYv%2BvSVsuMPxKIW98lz7ThDwGIRkGJuCZjINk67FK6Vw%3D%3D

**Comment by adityastic** [comment]
@refactor-droidyy would you like to work on it?

**Comment by refactor-droidyy** [comment]
@adityastic yeah sure.

**Comment by adityastic** [comment]
@iamareebjamal the token expired, please refresh the links whenever you are available. Thanks a ton

**Comment by adityastic** [comment]
@iamareebjamal it looks like the token in the links expired, please update the links whenever you come online. Thanks a ton again

**Comment by iamareebjamal** [comment]
They'll expire again.

**Comment by adityastic** [comment]
@iamareebjamal I'll download it

**Comment by iamareebjamal** [comment]
Updates

**Comment by adityastic** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11988517/71313450-f115f680-2430-11ea-8a39-f7331f6a3ca0.gif)
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/11988517/71313454-f3785080-2430-11ea-9d7e-b486ea2004d1.gif)

**Comment by adityastic** [comment]
@refactor-droidyy please have a look

**Comment by adityastic** [comment]
@refactor-droidyy any updates?

**Comment by refactor-droidyy** [comment]
@adityastic Right now my college is opening and I have to shift there I will do it in 2 days .
