### ISSUE TITLE
Navigation drawer header UI fix

### ISSUE THREAD

**Issue by tanmayrauth** [fossasia/badge-magic-android#564]
**Describe the bug**
Previously the header in navigation drawer was blank with unwanted view object with no appname

**To Reproduce**
Added Screenshot for this

**Expected behavior**
Removed unwanted padding and view object from header and added appname with expected padding.

**Screenshots**

![image](https://user-images.githubusercontent.com/18233626/71323447-3e5d9b00-24f9-11ea-83b2-a50cbed7261c.png)

**Would you like to work on the issue?**
Yes, I would like to work on this.

**Comment by tanmayrauth** [comment]
@adityastic  how can we add codeheat and fix label to it ?

**Comment by adityastic** [comment]
Only the maintainers have the access to do that. Don't worry I'll add them

**Comment by tanmayrauth** [comment]
Thanks
