### ISSUE TITLE
Change toasts to snackbars

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/badge-magic-android#58]
**Describe the chore**
Snackbars should be used instead of toasts for better UI.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Toast seems more appropriate as there is actually an error.

**Comment by mariobehling** [comment]
Please help to solve more higher priority issues e.g. https://github.com/fossasia/badge-magic-android/issues/14
