### ISSUE TITLE
F-Droid build doesn't work

### ISSUE THREAD

**Issue by xamanu** [fossasia/badge-magic-android#583]
**Describe the bug**
The current build on F-Droid doesn't seem to work. I tested it with two different Android devices. When clicking "Transfer" to the badge, it complains about `No GPS Found, Please Enable GPS from settings, despite GPS being allowed and activated.

**To Reproduce**
Install the app from F-Droid and try to transfer some content to the badge.

**Comment by adityastic** [comment]
@xamanu just tried, it works for me. Can you send a video for the same. Including a fresh install and a test in the video

**Comment by xamanu** [comment]
Dies this work? 
http://cloud.consciente.de/index.php/s/gR3Xjk8eT9MLxqE

**Comment by adityastic** [comment]
@xamanu it does not show what happened after you gave the permission. Try clicking on transfer button again

**Comment by xamanu** [comment]
Thanks for the great device and you looking into this problem!

Permission was given from the beginning, when the app starts up for the first time. Then I just show you the settings, without changing anything.

See here a new screen recording http://cloud.consciente.de/index.php/s/iwjRntybQiJG9kH

I had the same issue with two different phones (Android 9 and 10), and during the congress when I was at the table purchasing the badge, there were three people with the very same problem, just at this moment.

**Comment by adityastic** [comment]
@xamanu Perfect, can you please specify the devices you tested it on?

**Comment by xamanu** [comment]
Google Pixel 2XL with Android 10 (without GApps).
Google Nexus 5X with Android 8.1 (GApps installed on the system).

It seems to be a common problem. As said on the FOSSAsia table at the congress people started queuing up having this problem.

**Comment by fcartegnie** [comment]
Confirmed. 
No one could use that build at CCC, whatever their settings were. Android 9, OnePlus, and even Android 10

**Comment by adityastic** [comment]
@fcartegnie I'm investigating the issue, thanks for the support. As there is no crash, it is difficult for me to understand what might be going wrong here. But definitely we'll try to fix it within the next week

**Comment by adityastic** [comment]
@fcartegnie @xamanu got the issue, dropping a pr to fix it rn :)

**Comment by xamanu** [comment]
Many thanks! Let me know if I can test the apk somehow without looking into the building pipeline.

**Comment by adityastic** [comment]
@xamanu https://raw.githubusercontent.com/fossasia/badge-magic-android/apk/badge-magic-development-debug.apk try this out

**Comment by xamanu** [comment]
Works. Thank you!

**Comment by adityastic** [comment]
@xamanu perfect, it will be live on fdroid and app store with the next update, till then you can use this link as it will always contain the latest test apps. Cheers !
