### ISSUE TITLE
No message when saved clipart list is empty

### ISSUE THREAD

**Issue by tronku** [fossasia/badge-magic-android#588]
**Describe the bug**
There is a little issue in the UI of the app. If there are no items in the saved cliparts then a blank screen appears to the user which is confusing and gives a bad experience.

**To Reproduce**
Delete all the saved cliparts, if any. Go to saved clipart fragment from the nav drawer.

**Expected behavior**
User should be informed that there is no saved clipart.

**Screenshots**

![ezgif-2-870f847b6267](https://user-images.githubusercontent.com/31654207/71582147-df1e0d00-2b2e-11ea-90e8-148a08e17750.gif)

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         | Mi Note 5 |
|Android Version|  Oreo 8.1  |

**Would you like to work on the issue?**
Yes

**Comment by tanmayrauth** [comment]
Can i work on this issue?

**Comment by adityastic** [comment]
@tanmayrauth it is in progress atm. @tronku has a buffer of 7 days to complete this. Keep a check on the progress 👍

**Comment by tanmayrauth** [comment]
@tronku @adityastic Was there any progress in this issue?

**Comment by adityastic** [comment]
@tanmayrauth waiting for his reply

**Comment by tronku** [comment]
Sorry, I was a little busy, I will complete it soon
