### ISSUE TITLE
Shifting hideKeyboard function to onDrawerslide 

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/badge-magic-android#590]
**Describe the bug**
Right now the keyboard in the main screen hides only when the drawer is fully opened

**To Reproduce**
Launch the application and slide drawer.

**Expected behaviour**
The keyboard should hide on sliding little amount of drawer

**Screenshots**

![bluetooth_before](https://user-images.githubusercontent.com/44283521/71586948-eac6ff00-2b41-11ea-91b6-e9dedf699c4e.gif)

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
@iamareebjamal please give your thoughts on this issue

**Comment by iamareebjamal** [comment]
Not needed. It's not a bug in our code
