### ISSUE TITLE
Disable Send button when there is no bluetooth device connected

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#60]
**Describe the feature you'd like**
A message should show up when there is no bluetooth device connected. For example a toast message or an alert.

**Additional context**
We could also disable the send button when there is no bluetooth device connected.

**Would you like to work on the issue?**
Yes

**Comment by yatri1609** [comment]
@iamareebjamal Can I work on this issue?

**Comment by iamareebjamal** [comment]
Disabling it sounds reasonable

**Comment by yatri1609** [comment]
@iamareebjamal Cool, I'll disable the button when there is no bluetooth device connected

**Comment by yashk2000** [comment]
Do not do this. The app didn't require a Bluetooth device to be connected. It uses BLE. When a message is sent to the badge, the badge doesn't show up as a device. BLE is used and the message is transferred.

**Comment by yatri1609** [comment]
@yashk2000 Are you a mentor here ? Also there in this app there is nothing which can show that device is not there or BLE is not sending anything

**Comment by yashk2000** [comment]
This should not be done as when the message is sent using BLE, a Bluetooth connection is not required. Therefore if you check whether a device is connected via Bluetooth and disable the button then, the button will always be disabled. There is no way to detect if the LED Badge is there or not. If the badge is there and is on receiving mode, the message will be sent else nothing will happen. A message is always sent using BLE when send is pressed. If the device is there, it will receive it.

**Comment by yatri1609** [comment]
@yashk2000 Ohk got that. I thought there was something like that. Sorry for my misunderstanding

**Comment by liveHarshit** [comment]
This issue is not practical.
