### ISSUE TITLE
Application directly closes on back pressed

### ISSUE THREAD

**Issue by tanmayrauth** [fossasia/badge-magic-android#616]
**Describe the feature you'd like**
Application directly closes on back pressed. If an user clicks the back button unintensionally then the application is terminated . A small dialog box can fix this issue.

**Would you like to work on the issue?**
Sure

**Comment by adityastic** [comment]
We might not need this

**Comment by tanmayrauth** [comment]
But you might have seen this feature in many apps where it is used to avoid unexpected back clicks. Isn't it?

**Comment by iamareebjamal** [comment]
Yes, non standard apps. If you made a mistake, you can go back to the app using switcher in 2 clicks. We'll be making users deliberately click twice who want to exit the app. Why can't people who made a mistake click twice?

**Comment by tanmayrauth** [comment]
No worries. Thanks for quick look.

**Comment by tanmayrauth** [comment]
But one thing I have observed is that our app is missing the flow.
There is no home menu. I consider create badge to be home menu.

So if someone clicks back from eg. Settings fragment ideally they should land to home menu. 

But in our current situation if one clicks back from any fragment the app is closed.

Is this expected behaviour? I believe there should be a home menu.
