### ISSUE TITLE
Not able to display the full text of a six alphabet word when both marqee and invert led are on in effects

### ISSUE THREAD

**Issue by AdityaPrabhuCS** [fossasia/badge-magic-android#633]
**Describe the bug**

Not able to display the full text of a six alphabet word when both marqee and invert led are kept on in effects
**To Reproduce**

enter a six alphabet word and in effects keep both marqee and invert led on you can obtain the bug

**Expected behavior**

whole word should be displayed
**Logs**

no crashes
**Screenshots**

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         |redmi 6|
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

i would like to try and work on this issue
![Untitled](https://user-images.githubusercontent.com/59806748/72796109-c7850080-3c64-11ea-9068-fd217244b986.png)

**Comment by adityastic** [comment]
Thanks aditya, will look into it

**Comment by adityastic** [comment]
@iamareebjamal this is because of #356 . The 'a' infront actually has a black pixel. I can add a checkbox if we found a black pixel in the first column and this checkbox will only show up when there is a black pixel in the first column. Is there any other way we can handle this issue?

**Comment by adityastic** [comment]
@iamareebjamal this is because of #356 . The 'a' infront actually has a black pixel. I can add a checkbox if we found a black pixel in the first column and this checkbox will only show up when there is a black pixel in the first column. Is there any other way we can handle this issue?

**Comment by iamareebjamal** [comment]
Will think and get back to you

**Comment by adityastic** [comment]
@iamareebjamal Perfect

**Comment by iamareebjamal** [comment]
Let's go with your suggestion for now

**Comment by adityastic** [comment]
@iamareebjamal on it

**Comment by adityastic** [comment]
@iamareebjamal I just thought of something amazing. I remember adding 8 pixels, but I could have done something better. I could add 1 pixel at the start and the rest 7 at the end. So this would actually add the padding at the end and save us the hassle without any other options xD
