### ISSUE TITLE
bug: Pressing back button closes the app

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/badge-magic-android#635]
**Describe the bug**
Pressing back button for one time closes the app

**To Reproduce**
Open the app
Switch to any of fragment
Press the back button

**Expected behavior**
Pressing back button should give a pop up like toast or snackbar "To press back button again" if user wants to exit the app.

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0 |

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Intended behaviour
