### ISSUE TITLE
Flash and marquee effect are switched 

### ISSUE THREAD

**Issue by Poeschl** [fossasia/badge-magic-android#636]
**Describe the bug**

It seems that the flash and marquee effect has switched. After transferring to the magic badge the effects get switched. 
Flashing effect will be displayed as marquee effect and likewise the marquee effect. 

**To Reproduce**

Create any badge and select the flash or marquee effect. The animation selection selection doesn't matter. 

**Expected behavior**

When transfered to the magic badge the Leds should flash on flash or have the blinking border when selected. 

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         |OnePlus 6|
|Android Version|  10  |

**Additional context**

I used the export to see the stored values and the values are stored correctly. 
For example: Flash selected -> flash: true -> marquee on display. 

**Would you like to work on the issue?**

I can try to fix it, but first I want this bug be confirmed 😉

**Comment by TheLastProject** [comment]
I can reproduce this issue on my Fairphone 3 (Android 9).

Because the previews are correct, my assumption is that there is a small mixup made in the part that actually transfers it.

**Comment by adityastic** [comment]
@TheLastProject perfect, would you like to solve it? or I can do it tomorrow xD

**Comment by TheLastProject** [comment]
Probably won't be able to take a look at this before the weekend but I'm wiling to take a look if you haven't solved it yet by then. I think @Poeschl is willing to try too though?

**Comment by adityastic** [comment]
@TheLastProject great, let's wait if @Poeschl comments till tomorrow else I'll fix it

**Comment by Poeschl** [comment]
If one of you want to fix it, go on. 😉
I won't have time this weekend to do any development 😅

**Comment by dheerajkotwani** [comment]
@adityastic I would like to give it a try. Can I?

**Comment by adityastic** [comment]
@dheerajkotwani sure :)

**Comment by adityastic** [comment]
@Poeschl @TheLastProject unfortunately I cannot reproduce this error. @yashk2000 can you confirm if this happens with you

**Comment by Poeschl** [comment]
It seems that the effects are only switched after retrieving them via the 'stored bafgrs' menu.

When transferring them directly after creation it works fine.

**Comment by adityastic** [comment]
@Poeschl great let me check
