### ISSUE TITLE
Add Navigation Drawer to support different sections

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#64]
**Describe the feature you'd like**
Navigation Drawer will show if the Bluetooth device is connected or not and also support the About and FAQ section making the app more user friendly

**Additional context**
It could be somewhat similar to that in case of PSLab app

**Would you like to work on the issue?**
Yes

**Comment by yatri1609** [comment]
@iamareebjamal Can I work on this issue?

**Comment by yashk2000** [comment]
There is no need for this. The app doesn't connect to a device while sending data. And i was planning to add a navigation drawer any way when adding the about section. I'll add faqs there also.

**Comment by yatri1609** [comment]
@yashk2000 I could work on the FAQs since your are already working on About section

**Comment by yatri1609** [comment]
@yashk2000 And I already have navigation drawer ready.

**Comment by yashk2000** [comment]
@yatri1609 you should have asked me about creating the navigation drawer since I was already working on creating an about section. The best way to do that is by adding a navigation drawer. 

Sure, you can work on adding the FAQs after the About section with the nav drawer is done.

**Comment by yatri1609** [comment]
@yashk2000 Cool no problem. I'll work on FAQs when you are done with about section

**Comment by mariobehling** [comment]
Low priority. Please focus on moving forward the app through features first:
https://github.com/fossasia/badge-magic-android/labels/Priority%3A%20High
