### ISSUE TITLE
Having to deselect and select pencil in drawing

### ISSUE THREAD

**Issue by Lufteluke** [fossasia/badge-magic-android#643]
Entering drawing mode has the pencil selected, but it will not work. Deselecting and selecting it again solves the issue

Huawei P20 Pro (CLT-L29)
Android: 9.1.0.371

![ezgif-2-0bfd0bb14c62](https://user-images.githubusercontent.com/7013432/73608409-de134c00-45c2-11ea-80cc-ea27aec28598.gif)

**Comment by adityastic** [comment]
Hi @Lufteluke , can you try this out? https://raw.githubusercontent.com/fossasia/badge-magic-android/apk/badge-magic-master-debug.apk
