### ISSUE TITLE
Using Chrome Custom tabs 

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/badge-magic-android#645]
**Describe the feature**
For any url link the app redirect to default browser to view web content results in a huge context switch which isn’t customizable, and hence could lead to a terrible experience.

**Would you like to work on the issue?**
Yes

**Comment by adityastic** [comment]
We should rather focus on the working of the app than thinking about redirects or other links, let android handle it by itself. @iamareebjamal your thoughts?
