### ISSUE TITLE
Deploy at master failed

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badge-magic-android#652]
https://travis-ci.com/fossasia/badge-magic-android/jobs/285423923

AAB file not found

**Comment by adityastic** [comment]
@iamareebjamal looks like the screenshot dimensions are updated on google play store. Can you give me the new dimensions, the last build failed because of it

**Comment by iamareebjamal** [comment]
```
[09:15:47]: Google Api Error: invalidScreenshotDimensions: Invalid screenshot dimensions. - Invalid screenshot dimensions.
```

So informative, they should have written `Invalid screenshot dimensions` 2 times more to really dial it in

**Comment by adityastic** [comment]
Yep, lmao.

**Comment by iamareebjamal** [comment]
https://support.google.com/googleplay/android-developer/answer/1078870
