### ISSUE TITLE
Color of navigation bar.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#66]
**Describe the feature you'd like**
The color of the navigation bar is currently black. It should be made red to match the app theme.

**Would you like to work on the issue?**
YES.

**Comment by yatri1609** [comment]
@yashk2000 I don't see the navigation bar yet.

**Comment by yashk2000** [comment]
I meant the on screen navigation bar of the phone..where the home, back and multi tasking buttons are present.

**Comment by yatri1609** [comment]
@yashk2000 ohk since my phone doesn't have that so I don't have any idea about it..

**Comment by mariobehling** [comment]
Low priority. Please focus on moving forward the app through features first:
https://github.com/fossasia/badge-magic-android/labels/Priority%3A%20High
