### ISSUE TITLE
When trying to save a new drawing the application closes

### ISSUE THREAD

**Issue by carlosnewmusic** [fossasia/badge-magic-android#660]
**Describe the bug**
When trying to save a new drawing the application closes

**To Reproduce**
Display vertically, Draw, click on the save icon, and the application closes unexpectedly

**Expected behavior**
That will save the drawing and continue to function normally

**Logs**
How do I get them?

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         | VDF1400 |
|Android Version| 6.0.1   |

**Comment by refactor-droidyy** [comment]
@carlosnewmusic attach gif for the same.

**Comment by adityastic** [comment]
@carlosnewmusic can you test the latest version and report back about the issue?

**Comment by carlosnewmusic** [comment]
> @carlosnewmusic can you test the latest version and reporting back about the issue?

![Screenshot_20200220-114326](https://user-images.githubusercontent.com/19379457/74926635-7ccae580-53d6-11ea-8fb8-c17f4d063bd6.png)
Where I download the application in the f droid repositories the update does not appear

**Comment by iamareebjamal** [comment]
It takes some time for it to appear on F-Droid. Even more given that there was a recent fix in out config 5 days ago https://gitlab.com/fdroid/fdroiddata/-/commit/224a396caf18f883654eef2b2bf31df9da98b890

You can download the latest APKs from here - https://github.com/fossasia/badge-magic-android/tree/apk
