### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [fossasia/badge-magic-android#666]
there are several translation tools. 
[weblate](https://hosted.weblate.org/) 
[crowdin](https://crowdin.com/) 
[poeditor](https://poeditor.com/) 
[transifex](https://www.transifex.com/)

it would be easier than at github
I'm writing down my experiences here. But you have to decide what you want.
if you take value on opensource, you can use #weblate. otherwise i hang out a lot on #crowdin and #poeditor. poeditor is, that you can only translate if you know the link. in poeditor there is no overview of all created projects of all people. people who want to translate too, find your link only by chance. i think that's stupid.
at #transifex it can be that you are rejected or that it takes a long time until you are accepted.

**Comment by adityastic** [comment]
@iamareebjamal this would be amazing for translations

**Comment by iamareebjamal** [comment]
Let's go with weblate

**Comment by mondlicht-und-sterne** [comment]
don't know if you can do that. either you pay money or you sign up in some list. friends of mine gave it up after 8 weeks and went to crowdin or transifex.
but of course weblate would be opensource. the others are not.

**Comment by iamareebjamal** [comment]
https://hosted.weblate.org/projects/fossasia/badge-magic/
