### ISSUE TITLE
Send button gets disabled after one click

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#72]
**Describe the bug**
When you add a text and click on send button once, it gets disabled and then when we change some settings like speed or add marquee effect, the send button doesn't get enabled. One needs to exit the app and then again press send button 

**To Reproduce**
1. Open app and add text
2. Press `Send` 
3. Change settings like speed
4. Again try and press `Send`. (here it gets disabled)

**Expected behavior**
On changing any setting, `Send` button must be made clickable

**Logs**
N/A

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34381723/54749867-e3aab200-4bfb-11e9-9b16-5dd5039d7adb.gif)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         | Redmi 4 |
|Android Version|  Android 7.1.2   |

**Would you like to work on the issue?**
YES

**Comment by yashk2000** [comment]
The button gets enabled again after 10s. It was done to prevent the app from crashing due to IllegalArgumentsException. This is not an issue.
