### ISSUE TITLE
Fix bold typo in readme

### ISSUE THREAD

**Issue by cggvuhh** [fossasia/badge-magic-android#730]
**Describe the chore**
The bold action not closed in the readme.md file plz see in the screenshot given below-

### screenshot-
![now](https://user-images.githubusercontent.com/68186540/98464894-f0728400-21eb-11eb-8d23-dcb381fc6c66.PNG)

**Comment by Raunaksingh100** [comment]
i am working on this issue,
can you add a codeheat label for this issue??

**Comment by cggvuhh** [comment]
> can you add a codeheat label for this issue??

@Raunaksingh100 i have no rights for this
