### ISSUE TITLE
ScrollView on the Create Badge page doesn't work 

### ISSUE THREAD

**Issue by akri16** [fossasia/badge-magic-android#739]
**Describe the bug**

There is a scroll view in the fragments of the tabview on _Create Badge_ page. But it doesn`t work. The bug is seen when the keyboard opens.

**To Reproduce**

1. Open the app
2. Go to the Create Badge screen
3. Open Keyboard by click on the add text EditText
4. Try to scroll to view the obscured content

**Expected behavior**

It should scroll seamlessly

**Screenshots**

![WhatsApp Image 2021-01-05 at 11 50 41 (1)](https://user-images.githubusercontent.com/54491362/103635641-d72d5000-4f6e-11eb-843a-165f685284af.jpeg)

![WhatsApp Image 2021-01-05 at 11 50 41](https://user-images.githubusercontent.com/54491362/103635654-dac0d700-4f6e-11eb-916e-b276ee961bf4.jpeg)

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         | Vivo 1807|
|Android Version|   Oreo 8.1 |

**Would you like to work on the issue?**

**YES**

**Comment by adityastic** [comment]
Go ahead ;)
