### ISSUE TITLE
Send button becomes non clickable after pressing once for 10s.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#74]
**Describe the feature you'd like**
Right now, the send button is non-clickable after being pressed once for 10s. Instead it should just be disabled so that even if a user presses it, it appears to be clickable.

**Would you like to work on the issue?**

YES

**Comment by yatri1609** [comment]
This would be covered in my work on issue #60 so I would cover this part too as said in PR #63 that a message must appear and the color of button must be changed

**Comment by yashk2000** [comment]
I have put a comment on that pr. I don't think that should be done. As I said earlier, no Bluetooth connection os required. You cannot sense whether the badge is available or not without pressing the send button. If the badge is available, it will receive the message from BLE else nothing happens.

**Comment by yashk2000** [comment]
Please try this using the badge device once. You will see that no Bluetooth connection is required.

**Comment by yatri1609** [comment]
@yashk2000 I don't have the device actually 😅 so i can't check it out actually

**Comment by yatri1609** [comment]
@yashk2000 also I wanted to know if you are the mentor of this project ?

**Comment by liveHarshit** [comment]
Let me clear things. @yatri1609 First you need to analyze how the app is working. #60 is not a practical issue. Because led badge is not connected permanently, it sends the signal for one time then disconnect automatically.

**Comment by yashk2000** [comment]
I think having a device to check out how the app works is crucial to work on the project. I have a device and have checked these things. #60 is not required. And what @liveHarshit said is also correct.

**Comment by yatri1609** [comment]
@liveHarshit yeah I got that...

**Comment by yatri1609** [comment]
@yashk2000 that's no where written in the pre-requisites or something like that. Is that so @mariobehling ?

**Comment by yashk2000** [comment]
@yatri1609 you can contribute upto some extent without the hardware, but ultimately you will need it. You cannot make new features without seeing how they look on the badge and whether they actually work or not.

And no, I'm not a mentor for the project, just a contributor. But I'm always ready to help :)

**Comment by yatri1609** [comment]
@yashk2000 yeah so even that thing happened with the pslab last year when I was interning in that project and we got eventually got the device when we were selected for that project internship which was also a hardware project.

**Comment by yatri1609** [comment]
@yashk2000 Yeah exactly so eventually when I get selected I'll be having the device and will be able to work on larger part of the project to make it market ready. 

I understand not having a device is a barrier for now but I can surely work on some of the things which do not require for example adding About section, navigation drawer, etc. 

So if you agree on it I can work on things which do not require device for now and later when I have it I can work on the things which require device and you can always work on things which require device for now.

**Comment by yashk2000** [comment]
You can contribute to the app. All I'm saying is that it is better to have a hardware so as to properly understand how the app works.

**Comment by yatri1609** [comment]
@yashk2000 I understand but for now I don't have and eventually I will have it so currently while currently contributing for GSoC I don't think I'll be able have it. Is there any substitute if you know of the device ?

**Comment by yashk2000** [comment]
Of course you can work on issues which do not require the hardware. There's no need to ask me for that. But I'd like to keep working on the issues I have opened. If you find any other issues, not requiring the hardware do work on them to improve the app.

I don't think there is any substitute for the hardware. I too searched a lot for a substitute until I got the device, but was unable to find anything.

**Comment by yatri1609** [comment]
@yashk2000 Of course I'll be working on the issues which won't require the device for now and it's just that not having a device is not a barrier which even you should appreciate. And I'm saying this from my experience that not having device is not a barrier.

**Comment by yashk2000** [comment]
Sure @yatri1609 :)
