### ISSUE TITLE
Data in Saved Cliparts does not survive configuration change

### ISSUE THREAD

**Issue by akri16** [fossasia/badge-magic-android#741]
**Describe the bug**

The cliparts in _Saved Cliparts_ fragment doesn`t survive configuration changes like Screen rotation. It disappears and an empty list is shown.

**To Reproduce**

1. Launch the app
2. Select _Saved Cliparts_ from the drawer
3. Rotate the screen

**Expected behavior**

The data should remain the same before and after the rotation

**Screenshots**

https://user-images.githubusercontent.com/54491362/103667752-56854880-4f9c-11eb-9ff1-d73a7e4b0fba.mp4

**Smartphone Info:**

|               |   |
|---------------|---|
|Device         |Vivo 1807|
|Android Version|Oreo 8.1  |

**Would you like to work on the issue?**

**YES**

**Comment by adityastic** [comment]
Go ahead :)

**Comment by akri16** [comment]
@adityastic I am unable to reproduce the bug now :) I might have run into some special state before. Can I close this for now? Will reopen if it shows up again

**Comment by adityastic** [comment]
> @adityastic I am unable to reproduce the bug now :) I might have run into some special state before. Can I close this for now? Will reopen if it shows up again

Feel free to ✌️
