### ISSUE TITLE
Shift Pipelines from Travis CI to Github Action

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#742]
Tasks:

- [x] #743 - Write Basic Pipeline ( @adityastic )
- [x] Change Required Check from Travis to Github CI ( @iamareebjamal )
- [ ] Shift Secrets from Travis to Github Actions ( @iamareebjamal )
- [ ] - Add Deployment Pipeline based on the secrets ( @adityastic )

**Comment by adityastic** [comment]
@iamareebjamal let me know whenever you're done with shifting secrets, if possible also share the screenshot so I can map it to the exact variable

**Comment by iamareebjamal** [comment]
We cannot see Travis variables so have to regenerate and re-encrypt the files

**Comment by mariobehling** [comment]
@adityastic There are no variables entered. I am unclear what is required to be added.

**Comment by adityastic** [comment]
@mariobehling apparently the project does not build anymore due to android moving fast and gradle deprecating. I started the migration on my local machine but haven't gotten time to finish it yet. Once the project builds, I'll replicate it on github ci when I will have to set up secrets/env vars to be used by the project.
