### ISSUE TITLE
Make an icon for the app.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#77]
**Describe the chore**
There should be an icon for the app instead of the default android logo.

**Would you like to work on the issue?**
YES.

I was thinking of making the icon like the badgeyay website. Could you please give your opinions @iamareebjamal @mariobehling of how the app icon should be designed?

**Comment by yatri1609** [comment]
@yashk2000 Even I can help in designing part as I have experience in doing digital designing as well.

**Comment by yashk2000** [comment]
Thanks @yatri1609. Let's wait for the mentors to tell their idea of an icon.

**Comment by iamareebjamal** [comment]
Let's have a few mockups
