### ISSUE TITLE
Add CSS to the Github Page of this project

### ISSUE THREAD

**Issue by ghost** [fossasia/badge-magic-android#808]
**Describe the feature you'd like**
I've check the active Github page of this project and it has no CSS Cover. I want the CSS feature to be added in the active Github Page of this project.

**Screenshots**
![image](https://user-images.githubusercontent.com/70829126/142799442-d8b9d22b-e75b-414e-a7dd-1888902697c1.png)

**Additional context**
The active page looks dull without the CSS cover. 

**Would you like to work on the issue?**
Yes, I would love to work on this issue and add a good CSS Cover with match the niche of FOSSASIA.

**Comment by adityastic** [comment]
Sure, go ahead

**Comment by ghost** [comment]
I do have one query which I just realized, there is no html file, in this project, then how the Github pages are deployed? Should I add new files to the same code of the active Github page in this repository and the add a suitable CSS? Will it be fine?

**Comment by ghost** [comment]
I just figured out about the branch system. I will start working on it.

**Comment by adityastic** [comment]
> I do have one query which I just realized, there is no html file, in this project, then how the Github pages are deployed? Should I add new files to the same code of the active Github page in this repository and the add a suitable CSS? Will it be fine?

You can read up on Sphinx, the appropriate script that gets called is present in `script/upload-gh-pages.sh`. Use it to debug your changes as well, I'll need to add the command back to the release pipeline.

**Comment by ghost** [comment]
> > I do have one query which I just realized, there is no html file, in this project, then how the Github pages are deployed? Should I add new files to the same code of the active Github page in this repository and the add a suitable CSS? Will it be fine?
> 
> You can read up on Sphinx, the appropriate script that gets called is present in `script/upload-gh-pages.sh`. Use it to debug your changes as well, I'll need to add the command back to the release pipeline.

Can you please check the above PR?

**Comment by mariobehling** [comment]
Please refer to https://github.com/fossasia/badge-magic-android/pull/809
