### ISSUE TITLE
App couldn't detect my badge

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#85]
**Describe the bug**
I have a LED Badge which has its Bluetooth ID: FF:FF:2A:00:19:CA, and app is not able to detect it and send data while other app is able to detect and send data.

**Expected behavior**
It should detect this device and send data.

**Smartphone Info:**

| Device |Android Version| 
|----------|:-------------:|
| Redmi 4 | Android 7.1.4 |

**Additional context**
I tried CoolLED1248 app

**Would you like to work on the issue?**
YES, if it is a real issue to just an issue with my device. I'm not sure if it is a problem with my badge or with Scanning feature in the app.

**Comment by yatri1609** [comment]
@mariobehling @iamareebjamal Shouldn'e this app connect to any badge ? As I'm able to see my device in the bluetooth section but not able to connect it.

**Comment by ShridharGoel** [comment]
This app works for BLE devices

**Comment by yatri1609** [comment]
@ShridharGoel I checked in its configuration it said it is a BLE device

**Comment by cweitat** [comment]
Does your badge needs to press any buttons to enable the BLE function?

**Comment by yatri1609** [comment]
@cweitat No nothing like that... But I have ordered from Fossasia website..

**Comment by adityastic** [comment]
@iamareebjamal Please Close this

**Comment by lanrat** [comment]
I just ordered a new badge that also uses the CoolLED1248 app and is incompatible with this app. It does not appear to ever be detected.

**Comment by adityastic** [comment]
@lanrat hi sir, would you mind sharing the link of the badge with me?

**Comment by adityastic** [comment]
@lanrat are you talking about the vslab badge? If yes, would you mind contacting me personally. I would like examine the uuid of that badge in order to get it working

**Comment by lanrat** [comment]
I ordered this VBLab one: https://smile.amazon.com/gp/product/B07P5X28JY

I've attached a screenshot of the UUID from the [BLE Scanner App](https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner)
![ble](https://user-images.githubusercontent.com/164192/62263584-a0462880-b3d1-11e9-95ff-7c6ba1765cd4.png)

Also, it looks like this tag is 48x12 while the one demoed in this app is 44x11 .

Let me know if you need any other information.

**Comment by adityastic** [comment]
@lanrat yes sir, can you contact me personally regarding this support? I am sure we can get this through easier fast
