### ISSUE TITLE
Turning phone from vertical to horizontal results in deletion of text on badge preview

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#873]
Please ensure the text stays on the display preview when the user turns the phone from vertical to horizontal position.

Screenshots for the change:
![iss_240](https://user-images.githubusercontent.com/11988517/57187623-8058b300-6f0f-11e9-9f42-3028f197bfed.jpg)

**Comment by swapniltitoo** [comment]
Hey, I would like to work on this issue if still open. Thanks!

**Comment by Aryan20** [comment]
@hpdang @adityastic I checked the issue on the latest build, and it is not reproducible anymore. 
Considering the milestone was 1.5 and the latest is 1.7, it seems to be fixed along the way or was a fluke.
