### ISSUE TITLE
Create a full iOS version and generate a test app image in the apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#874]
Create a full iOS version with flutter and generate a test app image in the apk branch

**Comment by vivekismittal** [comment]
hi, can i get more info of this?

**Comment by adityastic** [comment]
> hi, can i get more info of this?

This might be a bit too broad. Let me break it down into multiple issues and link them to this thread today.

**Comment by vivekismittal** [comment]
yeah sure!
