### ISSUE TITLE
Update dependencies in the project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#877]
Since the inception of this project some time has passed and some library dependencies are out of date by now. Please update the dependencies of the project and ensure it still builds without errors.

**Comment by swapniltitoo** [comment]
I would like to work on this issue. If open please assign this to me! Thanks.

**Comment by adityastic** [comment]
> I would like to work on this issue. If open please assign this to me! Thanks.

Sure!

**Comment by AnsahMohammad** [comment]
@swapniltitoo  are you working on this ?
Otherwise i would like to work on this

**Comment by meghanagottapu** [comment]
@mariobehling can i work on this?

**Comment by jaivsh** [comment]
Hi @adityastic @mariobehling please assign me this! Thanks!

**Comment by ANUKULJHA1506** [comment]
@adityastic  please assign me this task.
