### ISSUE TITLE
Deploy Github Pages site using Github Actions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#885]
Previously we used Travis to create a GH pages branch and deployment at https://badgemagic.fossasia.org.

It has become easier to create pages using Github Actions. Please create a Github Action deploying the Readme.md as a page to https://badgemagic.fossasia.org.

**Comment by AnsahMohammad** [comment]
I'm interested in this. Can I work on this issue ?

**Comment by Satarupa22-SD** [comment]
can i be assigned to this issue?

**Comment by weshaan** [comment]
is this still on?

**Comment by mariobehling** [comment]
yes
