### ISSUE TITLE
Add a menu link to Privacy Policy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#901]
Change the following menu items:
1. Add a link "Privacy Policy" below "Feedback/Bug Reports" to https://badgemagic.fossasia.org/privacy/.
The page will be created shortly as well.

2. Change the link of "Buy Badge" to https://badgemagic.fossasia.org/shop/

![Screenshot_20240505_124719_Badge Magic](https://github.com/fossasia/badgemagic-android/assets/1583873/8a0c39f5-6eee-43ca-8330-84aa0cf5ddd9)

**Comment by kienvo** [comment]
I'll take this.
