### ISSUE TITLE
Animations (Marquee, Flash) in Badge Preview of the App

### ISSUE THREAD

**Issue by adityastic** [fossasia/badge-magic-android#93]
**Description**
The Badge should react according to the selected animation. Currently it only displays the Text onto the preview.

**GIF of How it should work**
![temp](https://user-images.githubusercontent.com/11988517/55049910-3d83ff80-5074-11e9-8325-3fec1bc8bd4b.gif)

**Would you like to work on the issue?**
YES

**Comment by yashk2000** [comment]
@adityastic that is not the marquee effect as shown by the device.

**Comment by adityastic** [comment]
@yashk2000  is the left marquee different in the actual device?
