### ISSUE TITLE
Implement more symbols.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/badge-magic-android#98]
**Describe the feature you'd like**
Some symbols such as cent, yen, pound are not yet implemented in the app. I would like to implement these symbols.

**Additional context**
I would also implement any other missing symbols that I find.

**Would you like to work on the issue?**

YES.

**Comment by adityastic** [comment]
@yashk2000 good luck with that

**Comment by adityastic** [comment]
@yashk2000 any updates on this?

**Comment by yashk2000** [comment]
I am working on it. I have implemented a few symbols. Will send a pr once few more are done. I will keep updating the list with any unimplemented character I find after sending the pr also.

**Comment by adityastic** [comment]
@yashk2000 great.

**Comment by yashk2000** [comment]
I am working on Implementing more symbols.
