### ISSUE TITLE
Add support for Spotled badges

### ISSUE THREAD

**Issue by eloydegen** [fossasia/badge-magic-android#983]
I bought the following badge from AliExpress: https://aliexpress.com/item/1005007123339205.html

It identifies as a "D451" badge, which I can't find on Google. The vendor app is called Spotled: https://play.google.com/store/apps/details?id=com.led.spotled

I assumed it would work with this app. Unfortunately, it does not. However, the app from the vendor does work, but it's less ideal.

I am not fully sure if they are incompatible, but the Play Store release of the app crashes when I try to send text and the badge doesn't react to anything done from the 2020 release from F-Droid.

**Comment by eloydegen** [comment]
I am not fully sure if they are incompatible, but the Play Store release of the app crashes when I try to send text and the badge doesn't react to anything done from the 2020 release from F-Droid

**Comment by Jhalakupadhyay** [comment]
hii @eloydegen does the app from the F-droid worked with the badge that you are using
